### ISSUE TITLE
Centrifuge Chain Block Explorer Bounty/Grant/RFP

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/centrifuge-chain#100]
# Why
As a user of Centrifuge Chain I want an easy way to explore blocks, chain data, events, etc. I want to be able to do this with a browser and no special tooling needed. 

# What
A block explorer similar to Polkascan, Etherscan, etc

# How
Possible approaches:
- fork https://github.com/polkascan/
- fork https://github.com/polkadot-js/apps

Brand it Centrifuge Chain specific, add the Centrifuge networks, publish new Docker images, etc.
Or engage with the team running polkascan 

## Branding
Re-use or lean on https://axis.centrifuge.io/ and https://github.com/centrifuge/axis

**Comment by emielvanderhoek** [comment]
We added Centrifuge Amber (testnet) to Polkascan.
https://polkascan.io/pre/centrifuge-amber

**Comment by philipstanislaus** [comment]
Awesome, thanks @emielvanderhoek !
