### ISSUE TITLE
Rewards: pallet-block-rewards implementation

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1000]
### Which part of the code is the issue addressing?

* Feature: https://github.com/centrifuge/roadmap/issues/163

### Description

Implements the `pallet-block-rewards`. This implies:
- Implementation
- Testing
- Benchmarks

### Research/based on
- See [specs](https://centrifuge.hackmd.io/9T9zAZaTRD6ZcHN-Gd_lzw?view)

**Comment by wischli** [comment]
Todos

- [ ] Create `pallet_block_rewards` based on the [rewards spec](https://centrifuge.hackmd.io/9T9zAZaTRD6ZcHN-Gd_lzw?view)
- [ ] Add to Centrifuge runtime: Rewards should be minted
- [ ] Add to Altair runtime: Rewards should be pulled from Treasury 
Probably requires adding an interface for handling the token origin in `<<pallet_rewards::Pallet::<T, I>> as GroupRewards>::reward_group which defaults to `T::Currency::mint_into`: Add interface Inflation<Currency> exposing fn inflate(amount) -> DispatchResult
  - [ ] Decide on Waterflow if MintedPerEpoc < N * RewardPerEpoc? Adjust reward for collators by just dividing rest amount by N?
- [ ] Benchmark `pallet_block_rewards`
- [ ] Benchmark `pallet_collator_selection`
- [ ] Benchmark `pallet_session`
- [ ] TBD: Add runtime API call to amount of claimable rewards
