### ISSUE TITLE
pallet-bridge migration: remove old storages

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1002]
### Which part of the code is the issue addressing?

- Cleaning

### Description

In https://github.com/centrifuge/centrifuge-chain/pull/978 we remove two storages: 

```rust
// Additional fee charged when transferring native tokens to target chains (in CFGs).
#[pallet::storage]
#[pallet::getter(fn get_native_token_transfer_fee)]
pub type NativeTokenTransferFee<T> =
StorageValue<_, u128, ValueQuery, <T as Config>::NativeTokenTransferFee>;

// Additional fee charged when transferring NFT tokens to target chains (in CFGs).
#[pallet::storage]
#[pallet::getter(fn get_nft_token_transfer_fee)]
pub type NftTokenTransferFee<T> =
StorageValue<_, u128, ValueQuery, <T as Config>::NftTokenTransferFee>;
```
Both are no longer used because the `pallet-fees` now handle that logic.
We should need to do a migration that remove the stored values in those storages.

### How will this affect the code base

Remove outdated data.

**Comment by mikiquantum** [comment]
n/a we can live with that
