### ISSUE TITLE
Rewards: Runtime API for list of currencies and claimable reward

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1063]
### Which part of the code is the issue addressing?

* Feature

### Description

- Allow the possibility to get the list of currencies an account has staked by Runtime API. 
- Allow the possibility to get the claimable reward amount for a list of currencies by Runtime API.

### Research/based on

Discussion thread here: by @mikiquantum in https://github.com/centrifuge/centrifuge-chain/pull/944#discussion_r998800249

**Comment by mikiquantum** [comment]
Fixed by #1124
