### ISSUE TITLE
Inconsistent use of bridge pallet accounts

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#1066]
### Which part of the code is the issue addressing?

* [x] Addressing a bug

### Description
We introduced a bug in the bridge logic when were refactoring some types and fees work. 

We are using three different bridge accounts depending on the operation triggered. Obviously we should always use the same one for incoming and outgoing transfers otherwise the bridge might not be able to return funds to a user that wants to get the CFGs back in their wallet. 
Accounts:
- Going out transfer: 4dpEcgqFmYGRSkRhTzVZjTG4uKoiB9VBB4Qi33LH73WsWXa4 (modlc/bridge)
- Going in transfer: 4dpEcgqFor2TJw9uWSjx2JpjkNmTic2UjJAK1j9fRtcTUoRu (modlcb/bridg)
- Bridge funds: 4dpEcgqFp8UL6eA3b7hhtdj7qftHRZE7g1uadHyuw1WSNSgH (modlchnbrdge) **SHOULD BE THE ONLY ONE USED!**

### Troubleshoot information:

This PR: https://github.com/centrifuge/centrifuge-chain/pull/899/files#diff-d788922e95fec28273169e1610a0faaacc47510e62417ea5f4954b6a4b5dd222L811 
Accidentally changed the `modlchnbrdge` to `modlcb/bridg` for incoming transfers

This PR: https://github.com/centrifuge/centrifuge-chain/commit/d899a8d94286286cd93fb340e7319abda9e99d71#diff-9a0a10ee5a7ac16e22f3c3d9a3948c63fef06278a3e8cef60b13e5d3e27798c5L348
Accidentally changed the `modlchnbrdge` (previous chainbridge::account_id()) to `modlc/bridge`

### Impact
This inconsistency would eventually cause low balance issues when moving native tokens back and forth.

### Action Plan:
- Rename chainbridge id (https://github.com/centrifuge/centrifuge-chain/blob/9638fdc4df4f09b1ffd473376cb3d42fd43b16ba/libs/types/src/ids.rs#L33) back to be `chnbrdge`
- Make use of the above ID in the bridge pallet in the transfer_native call. Basically pass to the runtime cfg_types::ids::CHAIN_BRIDGE_PALLET_ID instead of cfg_types::ids::BRIDGE_PALLET_ID as the trait T::BridgePalletId
- Add a migration that transfers all funds from `4dpEcgqFmYGRSkRhTzVZjTG4uKoiB9VBB4Qi33LH73WsWXa4` & `4dpEcgqFor2TJw9uWSjx2JpjkNmTic2UjJAK1j9fRtcTUoRu` to `4dpEcgqFp8UL6eA3b7hhtdj7qftHRZE7g1uadHyuw1WSNSgH`

**Comment by NunoAlexandre** [comment]
Closed in https://github.com/centrifuge/centrifuge-chain/pull/1067
