### ISSUE TITLE
Align Connectors and PoolSystem's token symbol and name sizes

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#1080]
## Context

> @offerijns I just realised that the `MaxTokenNameLength` and `*Symbol` that we set for the tranche metadata are higher than the limits we set on the connectors' messages:
>
> ```
> token_name: [u8; 32],
> token_symbol: [u8; 32],
> ```
> 
> How do you envision integrating this? Do we just truncate the metadata to fit in the connectors' 32 byte cap?

_Originally posted by @NunoAlexandre in https://github.com/centrifuge/centrifuge-chain/issues/1074#issuecomment-1311704523_

## Problem

`Connectors::add_tranche` looks up the given tranche's metadata and tries and converts its name and symbol - both bounded Vec's of 128 bytes at the moment - into  `token_name: [u8; 32]` and ` token_symbol: [u8; 32]`, respectively. This is an issue because we would have to truncate the original metadata to fit on these fixed-size arrays used to build the `AddTranche` message, which is not a good idea.

## Proposal

1. Align the upper bounds of both the tranche metadata on the `PoolSystem` level with the fixed-size set in the `AddTranche` message for said fields
2. When the original `name` and `symbols` set at the `PoolSystem` level are smaller than the size the Connectors message expects, pad the remaining empty space with 0's. This is needed since the connectors message, as a whole, needs to have a fixed size.

**Comment by NunoAlexandre** [comment]
cc @offerijns @mustermeiszer

**Comment by mustermeiszer** [comment]
I wonder what is the limit on the Ethereum side and what are the costs of having non 32-bytes values?

**Comment by NunoAlexandre** [comment]
I had a look at https://github.dev/centrifuge/connectors and the `tokenName` and `tokenSymbol` are parsed from `bytes32` to just `string` and then passed down to `RestrictedToken`'s constructor `constructor(string memory name_, string memory symbol_) ERC20(name_, symbol_) {}`. So I don't think we don't actually have a limit of 32, it's just a convention we started with on the Solidity side.

**Comment by NunoAlexandre** [comment]
Done in #1083
