### ISSUE TITLE
Renaming Pool Related Events

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#1130]
### Which part of the code is the issue addressing?
* [x] Refactoring

### Description
The current event naming needs some minor renaming before we go live.

* Change: `Pool::PoolCreated` to `Pool::Created`
   https://github.com/centrifuge/centrifuge-chain/blob/4a10ae7a7eaff0062e7aca3bcba4b4129e909bc8/pallets/pool-system/src/lib.rs#L384
* Change: `Pool::PoolUpdated` to `Pool::Updated`
   https://github.com/centrifuge/centrifuge-chain/blob/4a10ae7a7eaff0062e7aca3bcba4b4129e909bc8/pallets/pool-system/src/lib.rs#L398

### What are foreseen obstacles or hurdles to overcome?
Nothing, if we do it before indexing starts in the live-system

**Comment by mustermeiszer** [comment]
@wischli I am sorry, did not see you assigning to this one. I already created a PR

**Comment by wischli** [comment]
No worries, @NunoAlexandre shared this me as a potential candidate for a first PR but I positive the next one is already around the corner 😁
