### ISSUE TITLE
Pallet-Transfer-Allowlist

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#1144]
### Which part of the code is the issue addressing?
* [x] Feature

* Spec: https://centrifuge.hackmd.io/EL3WEpBuR7Gmzh904WYmaw

### Assumptions
* If a user has NO restriction set for a specific currency, then it MUST be assumed that every receiver is valid
* If a user has ONE restriction set for a specific currency, then ONLY allowlisted accounts are valid receivers
* The restrictions are checked on EVERY transfer via the `pallet_restricted_transfers::Pallet::transfer(..)` method
* Restrictions are set on a per currency base
   *E.g.: User A has a restriction set for CFG, which is only User B is a valid receiver for him*
* A receiver can be 
    * A local `AccountId32`
    * A XCM based `MultiLocation`
    * A connecotors based `DomainAddress`

### Description
A pallet that provides a means of allowing specific addresses to transfer to and only to transfer to those. The pallet implements a trait that others can consume.

The Config of the pallet should roughly look like the following: 
```rust
trait Config: frame_system::Config {      
    type Deposit: Get<BalanceOf<Self>>
}
```

and the pallet should define a type for a `Location` that is able to provide the following. This might just be the plain `Multilocation` from xcm, but maybe a custom struct is better suited.

```rust
impl From<AccountId> for Location {
   ...
}

impl From<Multilocation> for Location {
   ...
}
```

#### Traits
```rust
trait TransferAllowance<AccountId, Location> {
    type CurrencyId;
    
    fn allowance(send: AccountId, recv: Location, currency: SelfCurrencyId) -> DispatchResult;
}
```
Implemented by the pallet in two ways:
* Local AccountId based
    ```rust
    impl<T: Config> TransferAllowance<Self::AccountId, Self::AccountId> for Pallet<T> {
        type CurrencyId = CurrencyIdOf<T>;

        fn allowance(send: Self::AccountId, recv: Self::AccountId, currency: Self::CurrencyId) -> DispatchResult {
            if // Allowance set 
               // * If recv is part of list for currency
               //    * If yes -> has delay set
               //           * If yes -> has delay since adding passed
               //           * If not -> Fail
               //.     * If not -> Pass
               //  * If not -> pass 
            else 
                Ok(())
        }
    }
    ```

* MultiLocation based
    ```rust
    impl<T: Config> TransferAllowance<Self::AccountId, Multilocation> for Pallet<T> {
        type CurrencyId = CurrencyIdOf<T>;

        fn allowance(send: Self::AccountId, recv: Multilocation, currency: Self::CurrencyId) -> DispatchResult {
           if // Allowance set 
               // * If recv is part of list for currency
               //    * If yes -> has delay set
               //           * If yes -> has delay since adding passed
               //           * If not -> Fail
               //.     * If not -> Pass
               //  * If not -> pass 
            else 
                Ok(())
        }
    }
    ```

* DomainAddress based
    ```rust
    impl<T: Config> TransferAllowance<Self::AccountId, DomainAddress> for Pallet<T> {
        type CurrencyId = CurrencyIdOf<T>;

        fn allowance(send: Self::AccountId, recv: DomainAddress, currency: Self::CurrencyId) -> DispatchResult {
           if // Allowance set 
               // * If recv is part of list for currency
               //    * If yes -> has delay set
               //           * If yes -> has delay since adding passed
               //           * If not -> Fail
               //.     * If not -> Pass
               //  * If not -> pass 
            else 
                Ok(())
        }
    }
    ```

#### Extrinsic
* adding allowlist extrinsic, with parameters
    * `Origin::signed`
    * `who //Probably MultiLocation`
    * `CurrencyId`

    Logical requirements:
    * Can be called multiple times. As adding multiple accounts. The `Origin` is then only allowed to send to the specified addresses.
    * If there is a delay set, the changes will only be active after the delay passed. 
    * Need to lock some amount for storage reasons
    * Calling this after removing will reset `blocked_at` to `BlockNumber::MAX`

* removing allowlist extrinsics, with parameters
    * `Origin::signed`
    * `who //Probably MultiLocation`
    * `CurrencyId`
    
    Logical requirements:
    * Can be called on any existing combination of the parameters. 
    * Sets the `blocked_at` to `current_block + delay`.
    
* purge_storage extrinsics, with parameters
    * `Origin::signed`
    * `who`
    * `CurrencyId`

    Logical requirements:
    * Can be called in order to retain locked tokens.
    * Checks whether `blocked_at >= current_block && blocked_at != BlockNumber::MAX`
        * If passes: remove storage entry and free token
    
* adding a delay extrinsics, with parameters
    * `Origin::sined`
    * `delay: BlockNumber`

    Logical requirements:
    * Updates the delay to the given value
    
    Question:
    * How to handle changing a delay if there exist already one?
    
#### Storage and Types
* Allowances for a user
    ```rust
    #[pallet::storage]
    type Allowance = StorageNMap<
	    _,
	    (
		    NMapKey<Twox64Concat, T::AccountId>,
                     NMapKey<Twox64Concat, T::CurrencyId>,
		    NMapKey<Twox64Concat, Location>,
	    ),
	    AllowanceDetails,
	    OptionQuery,
    >;
    ```
* Type `AllowanceDetails`
    ```rust=
    pub struct AllowanceDetails<BlockNumber> {
        allowed_at: BlockNumber // Defaults to 0
        blocked_at: BlockNumber // Defaults to BlockNumber::MAX
    }
    ```
* Delay settings of a user
    ```rust
    #[pallet::storage]
    type Delay = StorageMap<_, T::AccountId, Twox64Concat, T::CurrencyId, Twox64Concat, T::BlockNumber>
    ```

### Research/based on
* User needs ensuring they can NOT send tokens accidentally to the wrong address
* User needs ensuring they can connect a hot wallet and a single person with access to millions of dollars

**Comment by thea-leake** [comment]
PR in review: https://github.com/centrifuge/centrifuge-chain/pull/1251
