### ISSUE TITLE
Clarify unhealthy loan definition

### ISSUE THREAD

**Issue by wischli** [centrifuge/centrifuge-chain#1158]
### Which part of the code is the issue addressing?

* [ ] Addressing a bug
* [x] Refactoring
* [ ] Feature

### Description

In `pallets/loan/`, the difference between `healthy` and `unhealthy` loans is not clear. It should be refactored for easier understanding:

```diff
- unhealthy
+ overdue
```

```diff
- LoanHealthy
+ LoanNotOverdue
```

### Research/based on

Based on @lemunozm's question on Slack and @offerijns answer

### How will this affect the code base

* Improves readability

### What are forseen obstacles or hurdles to overcome?

* None

**Comment by lemunozm** [comment]
These names no longer apply to pallet loans.
