### ISSUE TITLE
RtApi - Portfolio Composition of a pool

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#1174]
In the near future a pool -- if being an index -- will hold value in other pools and maybe also have loans being originated from it. In order to have a non-changing API for the Apps team we need a runtime API for this. 

### Tasks
- [ ] Sync with Apps team

### Draft 
```rust
fn portfolio(pool_id: PoolId) -> Vec<Holding> {
   ...
}

pub enum Holding {
    Loan {
        // TODO: Define with Apps what is needed here
    },
    Tranche {
          token: Currency,
          amount: Balance, 
          value: Balance
    }
}
```

**Comment by mustermeiszer** [comment]
I think this is really misleading. At a first thought at least. I have to think about it in more detail. 

Why do you think this is helpful?

**Comment by lemunozm** [comment]
This feature is done for the loans part. Check https://github.com/centrifuge/centrifuge-chain/pull/1457 description for a discussion about why keep this separate.

**Comment by mustermeiszer** [comment]
I will close this here. Once we have actual tranche holdings we should revisit
