### ISSUE TITLE
Use Centrifuge chain network ID For Mainnet S58 addresses

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/centrifuge-chain#118]
Similar to the description below, it would be great to have vanity addresses that separate the different networks.

FLNT: Flint
AMBR: Amber
CENT: Main net

```
$ subkey --network kusama vanity "ksma"
  Generating key containing pattern 'ksma'
  100000 keys searched; best is 190/237 complete
  200000 keys searched; best is 201/237 complete
  300000 keys searched; best is 207/237 complete
  ...
  1000000 keys searched; best is 225/237 complete
  2000000 keys searched; best is 225/237 complete
  best: 237 == top: 237
  Secret Key URI `0x6262bcafcf6e6abbea102a2dbafecb81c28e9737e2cbce3d3ead7bde47806ac4` is account:
  Public key (hex): 0xe6a979d75da9241c491f12b7e7c2cf015ba9202a4be4649a15b72a3a60e0e730
  Address (SS58): Hnksmako1TfL4rsVMnT798syHFdF8rtFQT3tNF4jqLdswZD
```
Take from [this PR](https://github.com/kusamanetwork/userguide/pull/48/files#)

**Comment by philipstanislaus** [comment]
@pstehlik I like the idea, but it might be an even better idea to use the address type of the `SS58` address format for that: https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)

**Comment by philipstanislaus** [comment]
The issue with enforcing vanity addresses is that users can’t use the vanity component for their own distinction of addresses anymore.

**Comment by philipstanislaus** [comment]
@pstehlik shall we use unique network identifiers as specified in SS58 instead? Might need to communicate with polkadot to "register" them, so they are official and won't be used by other networks.

**Comment by philipstanislaus** [comment]
PR: https://github.com/paritytech/substrate/pull/4748

**Comment by vedhavyas** [comment]
We would need to set it at the time when mainnet genesis is loaded in `chain_spec.rs`

```
set_default_ss58_version(Ss58AddressFormat::CentrifugeAccountDirect);
```

**Comment by philipstanislaus** [comment]
Added guide here: https://centrifuge.hackmd.io/UNeuvPB2QNq5-Ugp59xZ9Q?both
