### ISSUE TITLE
Implementation of `ChangeGuard` trait

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1207]
### Which part of the code is the issue addressing?

* Feature

### Description
```rust
/// Trait for checking changes before allowing them to be performed.
trait PoolChangeGuard {
   /// Associated pool where evaluate the change
   type PoolId;

   /// Reference a `Change` waiting to be released.
   type ChangeId;

   /// Information about the change the caller wants to do.
   type Change;

   /// Notify a `change` that affect somehow to `pool_id`.
   /// It will be "blocked" and referenced by the returned `ChangeId` until the conditions
   /// will be ok to allow the caller of this trait to perform the desired action.
   fn note(pool_id: PoolId, change: Self::Change) -> Result<Self::ChangeId, DispatchError>;

   /// Ask for a `change_id` if it's ready to proceed.
   /// An error will be returned if:
   /// - The change is not ready yet.
   /// - The change was already released.
   /// - The change has expired.
   /// If `Ok()`, the caller can proceed.
   fn released(change_id: Self::ChangeId) -> DispatchResult;
}
```

The implementation of this trait amalgamates changes from multiple locations of the codebase.

### Research/based on

- Currently, there is a similar trait called `PoolUpdateGuard`.
- Slack [Thread](https://kflabs.slack.com/archives/C04HJN404RK/p1674572242912299) of the conversation.
- Task that will make use of this: #1195

### What are forseen obstacles or hurdles to overcome?

- The `Change` type chosen by the implementation should contain information about the time.
We need to decide what is the relevant information to specify a `Change`.

**Comment by lemunozm** [comment]
I don't understand why the `PoolUpdateGuard` implementation found in `runtime/altair/src/lib.rs` is implemented in the runtime instead of the own `pallet-pool-system`. It is used by it, and all calls belong to or are accessible from the pool. 

Is there a non-obvious reason to implement it there?

**Comment by mustermeiszer** [comment]
No, the reason for this is that we want it to be a seperate pallet in the future. I.e. we want to be able to do checks that are not able in the pool-system in the future. I would not want to have a second trait! 

Lets define a single trait and use it both in the pool-system and in the loans pallet. WDYT? What I would propose is having the enum for changes defined as follows

```rust
#[amalgamtor::component]
pub enum LoanChanges {
    ANamedChange,
    AnotherNamedChange { pool_id: PoolId }
}

#[amalgamtor::component]
pub enum PoolCoreChanges {
     ANamedChange,
    AnotherNamedChange
}

#[amalgamator]
pub enum Changes {
   #[amalgamator::no_prefix]
    Loans(LoanChanges),
    PoolCore(PoolCoreChanges),
    #[amalgamator::as_sub]
    OtherVairant(Other)
}
```
*Note: The amalgamtor macro is not yet existing, just a convienence that makes it easy to create a "super" enum.*

which expands to something like: 
```rust
pub enum PoolCoreChanges {
    ANamedChange,
    AnotherNamedChange
}

impl amalagamtor::Component for PoolCoreChanges {
    fn variants() -> [&'static str, 2] {
          ["ANamedChange", "AnotherNamedChange"]
    }
}

pub enum LoanChanges {
    ANamedChange,
    AnotherNamedChange { pool_id: PoolId }
}

impl amalagamtor::Component for LoanChanges {
    fn variants_as_str_array() -> [&'static str, 2] {
          ["ANamedChange", "AnotherNamedChange { pool_id: PoolId }"]
    }
}

pub enum Changes {
       ANamedChange,
       AnotherNamedChange { pool_id: PoolId },
       PoolCoreANamedChange,
       PoolCoreAnotherNamedChange,
       OtherVariant(Variant)

}
```

The `trait Component` is just used in order to get the variants in the procedural macro `#[amalgamator]` as the compiler at this point has no knowledge about types but we can create a `TokenStream` from the `&static str`.

**Comment by lemunozm** [comment]
Ok! I see the point 😃 
Let me think more about this when I come back.

BTW, just the other day, I read about [subenum](https://docs.rs/subenum/latest/subenum/), which I think is quite similar to what you want to achieve with `amalgamator`.

**Comment by lemunozm** [comment]
To summarize pending open questions:
- Should `ChangeGuard` implementation knows that has been a simple a "loan change" or should it know which kind of change? Or even should it know the value of the variant that has changed? i.e:
  1. `ChangeGuard` implementation knows about `LoanChange`
  1. `ChangeGuard` implementation knows about `LoanChange::InterestRate`
  1. `ChangeGuard` implementation knows about `LoanChange::InterestRate(Rate)`

- Each change has different waiting times to get it done. Does that "waiting time" knowledge should be known by the `pallet-loans` and added as a parameter to `ChangeGuard` trait, or should the implementation of `ChangeGuard` who knows about this?
  - My first feeling is that it should be the first one, and we need to add a `Moment` parameter, but some parameters depend on epochs, and `pallet-loans` doesn't know about epochs, so it seems like `ChangeGuard` should know this info. Also, if `ChangeGuard` knows about this, it should distinguish which kind of loan change needs to be, to know if it should wait an epoch or not, so it should implement at least the second above option

**Comment by lemunozm** [comment]
Regarding the last point, maybe we can add a parameter with an enum as follows:
```rust
enum Waiting {
   Fixed(Moment),
   UntilNextEpoch,
}

fn note(pool_id: PoolId, change: Change, waiting: Waiting)
```

With this, the `ChangeGuard` implementation only needs to know if it was a `LoanChange`, not exactly what change

**Comment by mustermeiszer** [comment]
But this is not what the guard is for. It needs to know the changes and actually do some checks on them

**Comment by mustermeiszer** [comment]
> i. ChangeGuard implementation knows about LoanChange
ii. ChangeGuard implementation knows about LoanChange::InterestRate
iii. ChangeGuard implementation knows about LoanChange::InterestRate(Rate)

I would say this depends on the type of change. In general, our specs should define what kind of information is needed for the guard to know. For Rate I would assume that `ii` is sufficient.

**Comment by lemunozm** [comment]
> I would say this depends on the type of change.

And isn't this too much knowledge for the `ChangeGuard` implementation? I would like to extract what is needed for a `ChangeGuard` implementation and avoid to pass it concrete defined values (or types of changes) from the pallets.

What things are supposed to use by a `ChangeGuard` implementation? I mean, What will `Changeguard` do with the variant `LoanChange::InterestRate`?
