### ISSUE TITLE
Runtime API to expose current outstanding debt for loans

### ISSUE THREAD

**Issue by branan** [centrifuge/centrifuge-chain#1214]
### Which part of the code is the issue addressing?

* [ ] Addressing a bug
* [ ] Refactoring
* [x] Feature

### Description

The Centrifuge app frontend is currently querying the `loans` and `interest-accrual` storage to compute and display the current outstanding debt of all loans in a pool. It relies on the Substrate API's subscription system and  updates the displayed debt in real-time.

Ideally, we would consider the storage of interest rates and how loans use them to be an implementation detail. We need to expose an official API for the Centrifuge app to use for querying the active loans of a pool and their current debt.

### What are forseen obstacles or hurdles to overcome?

The new API itself is straightforward, but updating the frontend based on a mix of RPCs and storage subscriptions is kind of error-prone and messy.

**Comment by onnovisser** [comment]
What makes it messy for the frontend is that `multi()` and `entries()` calls don't return live subscriptions, so we're having to refetch manually based on events emitted from the chain anyways. So swapping out those calls with RPC calls shouldn't make it any more messy. See: https://github.com/centrifuge/apps/blob/main/centrifuge-js/src/modules/pools.ts#L1266

**Comment by lemunozm** [comment]
Is this issue something you will need for this release @onnovisser?

**Comment by lemunozm** [comment]
See: #1174

**Comment by lemunozm** [comment]
Close in favor of #1174
