### ISSUE TITLE
Add pools pallets to Centrifuge runtime

### ISSUE THREAD

**Issue by branan** [centrifuge/centrifuge-chain#1224]
### Which part of the code is the issue addressing?
* [x] Feature

### Description
Add the following pallets to the Centrifuge runtime:

* interest-accrual
* investments
* loans
* permissions
* pool-registry
* pool-system

Configuration for all of these should be nearly-identical between Development and Altair, and those are the configuration settings we will want.

Things to keep in mind:
* `PoolCreateOrigin` should be `EnsureRoot`
* `PoolDeposit` needs a final value

**Comment by mustermeiszer** [comment]
@branan can you add proxy setup here too?

**Comment by branan** [comment]
That's #1226
