### ISSUE TITLE
Centrifuge Chain: Nominating fails

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/centrifuge-chain#125]
`2019-11-29 12:29:51        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment`

**Comment by philipstanislaus** [comment]
Tested, works as expected.

**Comment by danielimkk** [comment]
Hey, what was the reason of error?
I`ve got the same, even though there is unbonded and transferable amount at account

**Comment by philipstanislaus** [comment]
Thanks for reporting this. Which testnet did you use?

**Comment by danielimkk** [comment]
I`m using another chain. I was just curios if your answer could help me

**Comment by philipstanislaus** [comment]
Got it – we did an upgrade of substrate to `master` which fixed the issue. I can't remember which commit is was, but the upgrade was done about 5 weeks ago, and it worked since then. Hope that helps!

**Comment by danielimkk** [comment]
Thank you, at least it helps to understand where an issue can be. Have a good day!
