### ISSUE TITLE
Inconsistent Pool Metadata Hash Between PoolRegistry.poolMetadata and PoolSystem.pool methods

### ISSUE THREAD

**Issue by filo87** [centrifuge/centrifuge-chain#1261]
### Which part of the code is the issue addressing?

* [X] Addressing a bug
* [ ] Refactoring
* [ ] Feature

### Description

`api.query.poolRegistry.poolMetadata()` and `api.query.poolSystem.pool()` deliver different IPFS hashes for the same pool. 
Results from `api.query.poolSystem.pool()` seem not to be updated after initialization.

### Research/based on

Dev Live
centrifuge-devel/1007

Centrifuge Parachain Collator
 v0.10.25
api v10.1.3
apps v0.124.2-161

### Steps to reproduce
![image](https://user-images.githubusercontent.com/11260745/225599662-9ef43aea-398d-4162-9332-f6c85ed378c7.png)
![image](https://user-images.githubusercontent.com/11260745/225599730-e94043af-6afc-4790-9ce9-88f6a5fb368f.png)

**Comment by mustermeiszer** [comment]
Thanks a lot for submitting! Will get to this next week. 

Cc: @branan and @wischli
