### ISSUE TITLE
Remove storage from pallet-loans in Altair

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1281]
### Description

Currently, Altair has only 1 closed loan.
We can remove it, nuking the storage of the pallet in a migration.

### How will this affect the code base

- Unlock the new `pallet-loans` to live in `altair` (the refactor)
- Allow removing the old pallet loans from the database, which unlocks/facilitates:
  - #1189
  - #1231
  - #1203
  - #908

### What are forseen obstacles or hurdles to overcome?

Wait for the next release

**Comment by mustermeiszer** [comment]
Nah, we need another democracy call for that. I would just introduce it in the next upgrade of the Altair runtime. 

Also we have typing and test with these kind of migrations compared to set storage.
