### ISSUE TITLE
Improve validator/docker build and push times in CI pipeline

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/centrifuge-chain#130]
Right now, docker build and push on Travis takes forever (~3 hours), which leads to extended downtime of our testnets if we need hotfixes for our validators. Options:

1. Check whether caching is setup on our Travis
2. Request a bigger Travis instance for our builds
3. Move build and push outside of Travis

**Comment by philipstanislaus** [comment]
- [ ] Ask Travis to increase resources?
- [ ] Paralellize tests

**Comment by vedhavyas** [comment]
Closing this as we moved to Github actions for build and push to docker has to come down to 1 hour from 3 hours
