### ISSUE TITLE
Loans: Write off policy with different triggers

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1305]
### Description

We can have different reasons for writing off a loan, not only overdue days. We need to model that:

From this [Slack conversation](https://kflabs.slack.com/archives/C050E3ZN2JU/p1680271126848299?thread_ts=1680107878.775689&cid=C050E3ZN2JU):

```rust
pub enum WriteOffTrigger {
    /// Number in days after the maturity date has passed
    PrincipalOverdueDays(u32),
    
    /// Seconds since the oracle valuation was last updated
    OracleValuationOutdated(Moment),
    
    /// Number in interest payments which are overdue
    NumberOfInterestPaymentsOverdue(u32),
}

pub struct WriteOffState<Rate> {
    /// If any of the triggers is valid, the write-off state can be applied
    pub triggers: Vec<WriteOffTrigger>,
    
    /// Percentage of present value we are going to write off on a loan
    pub percentage: Rate,
    
    /// Additional interest that accrues on the written off loan as penalty
    pub penalty: Rate,
}
```

**Comment by lemunozm** [comment]
I think we have an issue with the above model. 

Originally, we are applying the minimum `WriteOffState` that passes the condition. That means that I need to check between all States that have triggered the `WriteOffTrigger::PrincipalOverdueDays` to get the minimum of them. This works fine if we have only one kind of trigger, but if we compose this with other triggers is not easy to compute that "minimum". i.e:
- State1: overdue days: 4, oracle outdated 10
- State2: overdue days: 10, oracle outdated 4

What are the minimum State in this case?

cc @offerijns

**Comment by lemunozm** [comment]
Make sense!

**Comment by offerijns** [comment]
I meant, to sort it first by descending percentage, and if there are multiple states with the same percentage, then sort these by descending penalty.

**Comment by lemunozm** [comment]
Yeah, but suppose the following:
- Current state: percentage 20% penalty 10%
- Next state: percentage 15% penalty 90%

The "next state" can never be applied. Only I want to check this is not a possible use case.

**Comment by offerijns** [comment]
Ah I get what you mean now. I will think about this a bit :)

**Comment by offerijns** [comment]
@lemunozm I think this is an edge case of an edge case that we don't really need to support. Ultimately, the intention here is to apply the "most severe" write-off rule that currently applies. Generally speaking a write-down is more impactful than a penalty interest rate, so this makes sense to take precedence.

As a side note, would it make sense to rename the `WriteOffState` struct to `WriteOffRule` (so it becomes `a policy is a set of rules based on certain triggers`)? That seems clearer to me.

**Comment by lemunozm** [comment]
Ok!

> would it make sense to rename the WriteOffState struct to WriteOffRule

I like it!
