### ISSUE TITLE
feat: Extend `CustomMetadata` with Connectors-specific metadata

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#1350]
### Requirements

- Possible Connectors related information is derivable from the metadata

### Spec

**Adaption of the Metadata**
For this part of the change we need to change the existing struct.

```rust
pub struct XcmMetadata {
    /// The fee charged for every second that an XCM message takes to execute.
    /// When `None`, the `default_per_second` will be used instead.
    pub fee_per_second: Option<Balance>,
}

pub struct CustomMetadata {
    /// XCM-related metadata.
    pub xcm: XcmMetadata,

    /// Whether an asset can be minted.
    /// When `true`, the right permissions will checked in the permissions
    /// pallet to authorize asset minting by an origin.
    pub mintable: bool,

    /// Whether an asset is _permissioned_, i.e., whether the asset can only
    /// be transferred from and to whitelisted accounts. When `true`, the
    /// right permissions will checked in the permissions pallet to authorize
    /// transfer between mutually allowed from and to accounts.
    pub permissioned: bool,

    /// Whether an asset can be used as a currency to fund Centrifuge Pools.
    pub pool_currency: bool,
}

pub struct AssetMetadata<Balance, CustomMetadata: Parameter + Member + TypeInfo> {
    pub decimals: u32,
    pub name: Vec<u8>,
    pub symbol: Vec<u8>,
    pub existential_deposit: Balance,
    pub location: Option<VersionedMultiLocation>,
    pub additional: CustomMetadata,
}
```

We extend the existing metadata with the following struct:

```rust
pub struct ConnectorsMetadata {
    /// The "location" of the token on the 
    /// connectors domain. This can be used to actually
    /// derive both domain and also address for "adding"
    /// this currency to another domain via the 
    /// `AddCurrency` message.
    address: DomainAddress,
}

impl ConnectorsMetadata {
    fn location(&self) -> (Domain, [u8; 32]) {
        (self.address.domain(), self.address.address())
    }
}
```

and the `struct CustomMetadata` will subsequently be changed too

```rust
pub struct CustomMetadata {
    /// Connectors related metadata
    ///
    /// Not every currency variant has nor needs that.
    pub connectors: Option<ConnectorsMetadata>
    
    /// XCM-related metadata.
    pub xcm: XcmMetadata,

    /// Whether an asset can be minted.
    /// When `true`, the right permissions will checked in the permissions
    /// pallet to authorize asset minting by an origin.
    pub mintable: bool,

    /// Whether an asset is _permissioned_, i.e., whether the asset can only
    /// be transferred from and to whitelisted accounts. When `true`, the
    /// right permissions will checked in the permissions pallet to authorize
    /// transfer between mutually allowed from and to accounts.
    pub permissioned: bool,

    /// Whether an asset can be used as a currency to fund Centrifuge Pools.
    pub pool_currency: bool,
}
```

``` diff
- :warning: This change needs a migrations :warning:

- All existing storages in the metadata must be migrated
```

**Comment by NunoAlexandre** [comment]
_For the record_ 

Internally, we discussed this initial spec in how it was essentially introducing another way to represent the _location_ of a currency not using the `AssetMetadata.location` field but by introducing another optional one, ` pub connectors: Option<ConnectorsMetadata>`, to the `CustomMetadata` struct.

We agreed that this was still preferable given that by setting the `location` of an asset in the asset registry automatically makes it XCM-transferrable, which is undesired for Connector-remote tokens that we want to register in the AssetRegistry.

**Comment by NunoAlexandre** [comment]
Starting the work on this today, I noticed that the `DomainAddress` type is not suitable for this purpose. The type is defined as:

```rust
pub enum DomainAddress {
  /// A Centrifuge-Chain based account address, 32-bytes long
  Centrifuge([u8; 32]),
  
  /// An EVM chain address, 20-bytes long
  EVM(EVMChainId, [u8; 20]),
}
```

For the foreseeable future, we would only use this type for its `DomainAddress::EVM` variant, which is useful and suitable for us and our purpose since tokens on EVM are identified by a 20-byte long address, just like a regular wallet address.

*However*, the `DomainAddress:Centrifuge([u8; 32])` variant would never be useful for us since its purpose is to represent an account address, whereas tokens are represented using the `MultiLocation` type. We can argue that we could encode a `MultiLocation` of a Centrifuge token into a `[u8; 32]` and make that work, but we can also argue that's not a great idea.

With that in mind, I would propose that we consider two options:

---
### Option A

We introduce a new type designed to encapsulate the _location_ of an asset across different networks (Polkadot and EVM to start) and use that in the `ConnectorsMetadata` struct described in the original spec.

``` rust
enum ConnectorCurrencyLocation {
  Polkadot(MultiLocation),

  EVM(ChainId, [u8; 20]),
}
```

This is essentially the same solution as originally proposed but using a better suited type for representing the asset's location.

---
### Option B

As one notices going through `Option A`, the naming almost demand us to think about the `location` of the asset, which flags a duplication of concerns; i.e, a duplicate of the (already available) `AssetMetadata.location` field.

In this option, I suggest that:

- we use `AssetMetadata.location` alone instead, dropping `ConnectorsMetadata`
  This type is already future-proof since it allows us to represent any asset on any chain and network, whereas `DomainAddress` would need to be extended if we, for instance, wanted to represent a token native to another Polkadot parachain or native to another network all together.

  We can discuss the specific structure we would use to represent Connectors-EVM-Remote assets in a followup step.

- To address the issue around an asset being automatically XCM-transferrable once it has a set `AssetMetadata.location`, we add a new boolean field to `XcmMetadata` flagging whether the asset is XCM-transferrable and we use that in our XCM config to ensure that only the desired tokens are XCM-transferrable. Note this would indeed add an extra step to our XCM config but the computational cost of doing so - specially considering our expected flow of XCM transfers - is negligible. 

``` diff
pub struct XcmMetadata {
    /// The fee charged for every second that an XCM message takes to execute.
    /// When `None`, the `default_per_second` will be used instead.
    pub fee_per_second: Option<Balance>,

+  /// Flag whether this asset is XCM-transferrable. 
+  /// This will be used by the XCM config to allow/disallow transfers involving this token
+  pub transferrable: bool,
}
```

`NOTE:` This would also require a migration, in this case setting the `XcmMetadata.transferrable` field appropriately to all the registered assets in the AssetRegistry.

--- 

@mustermeiszer @wischli would love to get your feedback on the above ☝️ 🙏

**Comment by mustermeiszer** [comment]
Nice write up! 

I agree that given what we need `Option B` is the better route. But we are still missing something. With this change, the connectors logic will not be able to reason whether an asset is transferable via Connector messages, or am I missing something? 

* We need an additional field `connectors_token = bool`
* I would propose to also rename `transferrable` to `xcm_transferrable`

## Research Needed 
* We must research if we could get into trouble once we have parallel transfers -- using both XCM and Connector messages
   E.g. `USDC` on statemint: 
   * Will we only allow to transfer it to another Parachain with XCM native transfers?
   * If YES: Can we even integrate with other chains then - like moonbeam
   * If NO: Does this mean all integrations with Parachains must be based on using `Transact`

**Comment by NunoAlexandre** [comment]
@mustermeiszer thanks for the feedback 🙏 

>  the connectors logic will not be able to reason whether an asset is transferable via Connector messages

Great point, thanks for catching that!

> We need an additional field connectors_token = bool

Right, I'd say this bleeds the typical issue with using booleans: you need one every variation. How about adding a `transferability: Option<AssetTransferability>` field to `CustomMetadata` defined as `enum AssetTransferability { XCM, Connectors, All, None }`? Shall we have new methods of transfer in the future, we just extend this enum and won't need to keep adding booleans for the new methods.

> I would propose to also rename transferrable to xcm_transferrable

This should be eliminated by the suggestion above but, in any case, the reason I named it just `transferrable` is that it would live under `XcmMetadata`, so the scope is already engrained in the type hierarchy itself.

> ## Research Needed
> - We must research if we could get into trouble once we have parallel transfers -- using both XCM and Connector messages
> E.g. USDC on statemint:

The example of USDC from Statemint would be one where we would be talking about a Polkadot-native asset, which in nature should be XCM-transferrable, or else we wouldn't be able to transfer USDC from Statemint to the Centrifuge chain.

I guess the problem is, what if we want to use Statemint as a Connector-remote currency? As in, that due the nature of Connector-specific currencies, we wound't want them to be transferrable through XCM? I don't know the answer to be honest. But maybe because I don't _fully_ understand why those assets shouldn't be transferrable. But in the case of Statemint's USDC, we are clearly looking into an edge case where both transfers should be allowed and if we can't do that, we probably have to rethink our approach; maybe we wrap Statemint's USDC?

Would love to hear more from you (@mustermeiszer) and maybe from @offerijns  as well on this 🤩

**Comment by wischli** [comment]
Regarding the general question: I am also favoring `Option B`. Since we have less than 10 registered assets so far, the migration definitely is not an issue. 

> Right, I'd say this bleeds the typical issue with using booleans: you need one every variation. How about adding a `transferability: Option<AssetTransferability>` field to `CustomMetadata` defined as `enum AssetTransferability { XCM, Connectors, All, None }`? Shall we have new methods of transfer in the future, we just extend this enum and won't need to keep adding booleans for the new methods.

I like the approach. We should keep in mind that if we add more options, we might have to rephrase `All` and might want to start with a variant allowing `XCM` and `Connectors` which is not named `All`. 

>  I don't know the answer to be honest. But maybe because I don't fully understand why those assets shouldn't be transferrable

Same here. Once USDC is natively supported on Statemint, can we expect transfers between Ethereum and Statemint (and thus Polkadot chains) which don't create wrapped USDC on the recipient chain? Or would this only be possible by transferring via Circle, e.g. `Ethereum <-> Circle <-> Polkadot`?

**Comment by NunoAlexandre** [comment]
> I like the approach. We should keep in mind that if we add more options, we might have to rephrase `All` and might want to start with a variant allowing `XCM` and `Connectors` which is not named `All`.

Very good point! Given that we don't plan on having new transferring methods every month, this is nothing we can't address with a migration but definitely something good to keep in mind. We can also choose to make it list, using `BoundedVec`, where we list the specific methods we allow for; However, this approach also requires a migration if we add a new method and want most/all tokens to be supported by it, as we would need to extend that list with said new method for each toke of interest.

**Comment by offerijns** [comment]
> Same here. Once USDC is natively supported on Statemint, can we expect transfers between Ethereum and Statemint (and thus Polkadot chains) which don't create wrapped USDC on the recipient chain? Or would this only be possible by transferring via Circle, e.g. Ethereum <-> Circle <-> Polkadot?

Transfers between these will still create wrapped tokens, as they are basically issued by the bridge rather than by Circle. There is a workaround for that, the Circle Cross-Chain Transfer Protocol: https://www.circle.com/en/cross-chain-transfer-protocol But I expect this to take quite a while until it works on many chains.

> I guess the problem is, what if we want to use Statemint as a Connector-remote currency? As in, that due the nature of Connector-specific currencies, we wound't want them to be transferrable through XCM? I don't know the answer to be honest. But maybe because I don't fully understand why those assets shouldn't be transferrable.

I don't know if I fully understand the issue. But if you are talking about, as an example, Avalanche Connector Wrapped USDC on Centrifuge, I think they should not be transferrable through XCM not for any security reason (afaik), but simply because there's no sane use case for that. These are specifically issued by Connectors and only make sense on Centrifuge Chain.

**Comment by NunoAlexandre** [comment]
> I think they should not be transferrable through XCM not for any security reason (afaik), but simply because there's no sane use case for that. These are specifically issued by Connectors and only make sense on Centrifuge Chain.

Thanks, this is also my understanding 👍

**Comment by NunoAlexandre** [comment]
_The below is a v2 iteration on the original spec given all the discussion and details we are coming to agree on above. I will be updating this as further discussion takes place in follow up comments._

## Spec v2

### Requirements

- In the asset registry, we should be able to store and therefore lookup whether:
  - An asset is XCM-transferrable or not
  - An asset is Connector-transferrable
- Connector-wrapped tokens should have a `AssetMetadata.location` that encapsulates the EVM chain id and the specific EVM address of said token
  - We, therefore, can implement a lookup for Connector-wrapped assets that knows how to lookup that data from the asset's `location`
  - The XCM config should respect if the asset is XCM-transferrable or not
  - Connectors should respect if the asset is XMC 

### Code changes

#### 1. Extend the `CustomMetadata` type

We extend the `CustomMetadata` struct by adding a new `transferability` field:

``` diff
pub struct CustomMetadata {
	/// XCM-related metadata.
	pub xcm: XcmMetadata,

	/// Whether an asset can be minted.
	/// When `true`, the right permissions will checked in the permissions
	/// pallet to authorize asset minting by an origin.
	pub mintable: bool,

	/// Whether an asset is _permissioned_, i.e., whether the asset can only
	/// be transferred from and to whitelisted accounts. When `true`, the
	/// right permissions will checked in the permissions pallet to authorize
	/// transfer between mutually allowed from and to accounts.
	pub permissioned: bool,

	/// Whether an asset can be used as a currency to fund Centrifuge Pools.
	pub pool_currency: bool,
+
+       /// The ways this token is transferrable from/to this chain
+       pub transferability: AssetTransferability,
}

+ pub enum AssetTransferability {
+   /// The asset is only transferrable through XCM
+   Xcm,
+    
+   /// The asset is only transferrable through Connectors
+   Connectors,

+   /// The asset is transferrable through all available options.
+   /// NOTE: Once set to `All`, the asset is automatically transferrable through any eventual new option being added at a later stage. A migration might be required if that's undesirable.
+   All,

+   /// The asset is not transferrable
+   None,
+ }
```

### 2. Adapt XCM config

- Ensure that we verify that the asset's `AssetTransferability` includes `Xcm` and fail otherwise
- Extend the tests to cover both code paths

### 3. Connectors

- Ensure that we verify that the asset's `AssetTransferability` includes `Connectors` and fail otherwise
- Design a trait that deconstructs the `location` of an asset and return the useful pieces
   For Connectors v2/v3, this means being able to lookup the EVM chain and EVM address from the `location` of the asset when calling `AddCurrency`


--- 

Thrilled to get another round of eyes on this 🏄‍♂️

**Comment by mustermeiszer** [comment]
> Good point but I thought that's a simple we should have in place anyways in the transfer and transfer_tranche extrinsics, no? They are still transferrable through Connectors, just not through the general Transfer message/extrinsic.

I agree, but I am not sure, how we can check that in the connectors logic without commiting to the `enum CurrencyId`. 

 > Connectors should respect if the asset is XMC
 What does this mean?
 

> AFAIK we are only planning on supporting transferring Connectors-wrapped stable coins through Connectors. So setting the currently registered ForeignAssets to ::Xcm is safe and sensible for the current set.
I agree!
 

Other than the above, the spec looks really good!!

**Comment by NunoAlexandre** [comment]
> > Good point but I thought that's a simple we should have in place anyways in the transfer and transfer_tranche extrinsics, no? They are still transferrable through Connectors, just not through the general Transfer message/extrinsic.
> 
> I agree, but I am not sure, how we can check that in the connectors logic without commiting to the `enum CurrencyId`.


Right 🙃 One simple solution could be to pass a trait impl to the connectors pallet that checks `is_tranche_token(x: T::CurrencyId) -> bool`. 

Another, more structural approach would be to have a `TokenType` field in the `CustomMetadata` instead of `AssetTransferability` which would be something like `enum TokenType { Utility, StableCoin,  ConnectorsWrapped, TrancheToken, etc }` and on Connectors we ensure that the token type is `ConnectorsWrapped` for `Transfer` and `TrancheToken` for `TransferTrancheToken`; 

On the one hand I like this idea because we are just storing facts about each asset's nature but on the other hand it also makes it possible for, amongst a lot of other combinations, set a `CurrencyId::ForeignAsset` as a `TrancheToken`, or a `CurrencyId::Tranche` as a `ConnectorsWrapped`, which is an absolute no-go for me.
 
> > Connectors should respect if the asset is XMC
> 
> What does this mean?

Sorry about that, I must have moved text around or forgot what I was writing. Fixed the original text, thanks for the catch!

> > AFAIK we are only planning on supporting transferring Connectors-wrapped stable coins through Connectors. So setting the currently registered ForeignAssets to ::Xcm is safe and sensible for the current set.
> 
> I agree!

🏄‍♂️  nice

> Other than the above, the spec looks really good!!

Thanks buddy 💛  we are getting there

**Comment by mustermeiszer** [comment]
Yes, I totally agree. let's go with a trait.

**Comment by NunoAlexandre** [comment]
> Yes, I totally agree. let's go with a trait.

Great! Updated the spec above 👍  Thanks for your careful insight!

**Comment by wischli** [comment]
> * trait that offers a `is_tranche_token(T::CurrencyId) -> bool, for the purpose of checking the previous two points

If nobody has startet working on this, I would include this in my (soon to be published) WIP PR for adding extrinsics and inbound message handlers.

**Comment by NunoAlexandre** [comment]
> > * trait that offers a `is_tranche_token(T::CurrencyId) -> bool, for the purpose of checking the previous two points
> 
> If nobody has startet working on this, I would include this in my (soon to be published) WIP PR for adding extrinsics and inbound message handlers.

Yeah that would be great, it fits well in that PR's scope 👌  thanks

**Comment by NunoAlexandre** [comment]
> For completeness: #1357 does not solve this requirement. Totally fine with a subsequent PR. It's definitely a requirement for #1364.

Absolutely. Let's wrap that PR first and I will follow up on that specific requirement right after 👍

**Comment by NunoAlexandre** [comment]
Done in https://github.com/centrifuge/centrifuge-chain/pull/1393
