### ISSUE TITLE
Traits: Add `TimeAsSecs` trait

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1360]
### Description

We use the trait `UnixTime` everywhere to get the time as secs. We can use a trait wrapper over it (`TimeAsSecs`) that transforms the returned `Duration` time directly to seconds, avoiding confusion about what the time unit should be (`Moment` should be secs? millis? mins?) in some places.

Implementation draft:
```rust
trait TimeAsSecs: UnixTime {
    type Seconds: From<u64>; //u64 is the representation for Duration::as_secs()

    fn now() -> Self::Seconds {
        UnixTime::now().as_secs().into()
    }
}

// Auto implementations for any UnixTime type
impl<T: UnixTime> TimeAsSecs for T {}
```

**Comment by mustermeiszer** [comment]
Thanks for creating this! Should be trivial to clean up the codebase with this.

**Comment by lemunozm** [comment]
Wondering if makes sense to have a `Second` generic when the own `Duration` type from `UnixTime` is `u64`.

**Comment by mustermeiszer** [comment]
Probablz not ^^
