### ISSUE TITLE
Bug: Command line flag for using remote relay chain on Altair/Centrifuge node doesn't work

### ISSUE THREAD

**Issue by Curu24** [centrifuge/centrifuge-chain#1365]
Hello,

I tried to run Altair/Centrifuge collator with relay-chain-rpc-url flag to specify a remote relay chain RPC to be used instead of the embedded one but the node process ignores it and starts syncing relay chain locally. When provided with 2 relay-chain-rpc-url flags it crashes with this error:
```
Started centrifuge node.
error: The argument '--relay-chain-rpc-url <RELAY_CHAIN_RPC_URL>' was provided more than once, but cannot be used multiple times
Usage: centrifuge [OPTIONS] [-- <RELAYCHAIN_ARGS>...]
        centrifuge <COMMAND>
For more information try '--help'
centrifuge.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
centrifuge.service: Failed with result 'exit-code'.
```
Here is the full config
```
ExecStart=/usr/local/bin/centrifuge \
  --name Polkadotters \
  --base-path '/var/lib/centrifuge' \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --execution wasm \
  --wasm-execution Compiled \
  --collator \
  --chain centrifuge \
  --parachain-id 2031 \
  --rpc-port=9933 \
  --ws-port=9944 \
  --bootnodes /ip4/34.159.117.205/tcp/30333/ws/p2p/12D3KooWMspZo4aMEXWBH4UXm3gfiVkeu1AE68Y2JDdVzU723QPc \
  --public-addr /ip4/146.59.70.153/tcp/30333 \
  --listen-addr /ip4/0.0.0.0/tcp/30333 \
  --state-cache-size 0 \
  --log main,info \
  --relay-chain-rpc-url ws://57.129.1.46:9944 \
  --relay-chain-rpc-url ws://194.163.154.254:9944 \
  ```

**Comment by lemunozm** [comment]
Hi @Curu24,

It seems like you only can specify one URL as the relay chain. If you want to use `ws://194.163.154.254:9944` then you can not use the previous one `ws://57.129.1.46:9944`

**Comment by Curu24** [comment]
> Hi @Curu24,
> 
> It seems like you only can specify one URL as the relay chain. If you want to use `ws://194.163.154.254:9944` then you can not use the previous one `ws://57.129.1.46:9944`

Not really. As I mentioned with one url it ignores that flag completely. Plus on parachains where this feature works, there are no problems with providing multiple urls - which makes sense, because you don't want to rely on single relay node especially with more parachains connected to it.

**Comment by lemunozm** [comment]
Have you tried to specify only one flag but several values? 
Something like:

```sh
--relay-chain-rpc-url ws://57.129.1.46:9944,ws://194.163.154.254:9944
```

The doc for this flag found in Cumulus can expect several arguments

**Comment by Curu24** [comment]
> Have you tried to specify only one flag but several values? Something like:
> 
> ```shell
> --relay-chain-rpc-url ws://57.129.1.46:9944,ws://194.163.154.254:9944
> ```
> 
> The doc for this flag found in Cumulus can expect several arguments

for this setup I got following error:
`error: Invalid value 'ws://57.129.1.46:9944,ws://194.163.154.254:9944' for '--relay-chain-rpc-url <RELAY_CHAIN_RPC_URL>': invalid port number`

**Comment by lemunozm** [comment]
Not sure what the delimiter is, and now I can not test it. By default, it is `,` but it seems it has been overwritten, maybe a simple space works?

**Comment by lemunozm** [comment]
From the [cumulus readme](https://github.com/paritytech/cumulus), maybe what you're looking for is `--relay-chain-rpc-urls`, what is used as follows:

```sh
--relay-chain-rpc-urls \
    "ws://relaychain-rpc-endpoint:9944" \
    "ws://relaychain-rpc-endpoint-backup:9944" \
```

Does this work for you?

**Comment by lemunozm** [comment]
Ok, I see. What version are you using o the centrifuge node? Probably is not a recent one.

You can know it with the following command:

```sh
 /usr/local/bin/centrifuge --version
```

**Comment by Curu24** [comment]
it's 0.10.26, so up until today it was the recent one

**Comment by wischli** [comment]
Unfortunately, v0.10.27 will be the first version which supports this command together with collation. We added support in #1241, see [here](https://github.com/centrifuge/centrifuge-chain/pull/1241/files#diff-de6b9cfd1a256da7900d35e26aa7279bd713110e68e91b52616befb7397848dfR481), which is not part of 0.10.26. 

Due to the addition of EVM support in v0.10.27, you probably have to wait with updating your client until the runtime code is updated on Altair and Centrifuge.

And just for clarification, for now, `relay-chain-rpc-url` seems to be the correct CLI command even though the manual states `relay-chain-rpc-urls` but this throws. Will check if this is the case on Cumulus master and if so open an issue for the inconsistency.
