### ISSUE TITLE
Loans:  Fixed maturity with extension

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#1405]
### Description
Add an option to include a # of extension days in a fixed maturity asset, which enables extending the maturity by those # of days without going through the change guard.

The benefit is that for internally priced assets, the valuation can depend on the correct maturity date. 

- [ ] Add
```rust
enum MaturityDate {
  Fixed {
    date: Moment,
    extension: Moment,
  }
}
```
- [ ] Maturity date can be modified as long as
    ```rust
    new_maturity_date = old_maturity_date + (prev_extension_days - remaining_extension_days)
    remaining_extension_days = prev_extension_days - (new_maturity_date - old_maturity_date)`
    ```
  Basically the extension days are reduced with the same amount as the maturity date is increased.

**Comment by lemunozm** [comment]
This issue is continued in this [slack thread](https://kflabs.slack.com/archives/C050E3ZN2JU/p1688045625804219)
