### ISSUE TITLE
Loans: add `remark` to loan transactions

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#1409]
### Description

Add `remark: IpfsHash` (where `IpfsHash = [u8; 46]`) as an extrinsic argument, which is emitted in the events but never stored, to all loan transactions. This would enable borrowers to add documentation about the transactions to these in off-chain storage (IPFS).

**Comment by mustermeiszer** [comment]
@offerijns I was wondering whether we should rather provide a `Remark` pallet that takes a single `Extrinsic` or an `BoundedVec<Extrinsic>`. Then the event is emitted alongside the called extrinsic. Would allow issuers to extend this behaviour to any extrinsic/batch being called and we must not take care of refactoring loans or other pallets when changing/extending this.

**Comment by offerijns** [comment]
Interesting idea! We should investigate how much work this would be to index in the subquery. By default it indexes specific events (e.g. listens to `loans.Created`), so it would need to listen to all `remark.Remarked` events and tie this back to the asset tx. But it would indeed be nice to have this implicitly for all events across all pools.

**Comment by mustermeiszer** [comment]
I think the main advantage of having a slim pallet would be 
* batch is part if the extrinsic input &rarr; we can include the called extrinsic in the remark event
* we can use an enum type that not only provides ipfs hash but also string values or so

From a business perspective it would be:

* issuer wants to tie some action `A` to some documenting string/hash `Doc` &rarr; uses `Remark(Doc, A)`

**Comment by lemunozm** [comment]
Is this feature required for August's release?

**Comment by lemunozm** [comment]
Specs for a future fix: https://centrifuge.hackmd.io/koHrwp3URbuai__g3dJGtQ

**Comment by lemunozm** [comment]
This issue does not require implementation by our side, and can be achieved using the `pallet_utilities` and `pallet_remark` (or `frame_system::remark_with_event`). More in this [slack thread](https://centrifugedao.slack.com/archives/C05DX0RH1T3/p1689323303521659).

**Comment by lemunozm** [comment]
I think could be closed then
