### ISSUE TITLE
feat: Pallet Foreign Investments

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#1418]
Internal spec: https://centrifuge.hackmd.io/@rxJQ-iCrT9eYElX4L2WMmA/S1fmJty_s?type=view#pallet-foreign-investments

![foreign](https://github.com/centrifuge/centrifuge-chain/assets/7075260/419a5c31-c053-4181-9fbd-921335138c46)

Note: this issue serves as a tracking item for this work and for ease of discussion. The details of the implementation will stay in the spec.

**Comment by NunoAlexandre** [comment]
@mustermeiszer to make sure I gather the full picture of this pallet;

The `Connectors` pallet will operate with a `Investments` trait which will underneath will communicate with this new `pallet-foreign-investments`. This pallet will be responsible for 1) submitting a swap order to the also new `OrderBook` pallet and, when said order is full-filled, for 2) submit the investment order using the right pool currency (i.e, the outcome currency of the submitted swap in step 1).

Do I miss(understand) anything so far?

Given that step 3 is async, step 4 needs to be triggered. Do we want the order book to handle that or do we want for example to have the foreign-investments pallet checking for the status of a submitted order and follow up on it once it's fullfilled? E.g. with a hook that will be triggered at every block? What are your ideas around that?

**Comment by mustermeiszer** [comment]
All correct. But we are missing the lately added `Executed*` messages in this context. So `pallet-foreign-investments` would need to furthermore take care of 

* sending a `ExecutedInvestOrder` in this example back to the right domain

This is gets increasingly complex with updating orders in the fly (see state machine graphic in the spec). 

To reiterate, the spec is WIP and we should write it to a full spec together on the fly. WDYT?

**Comment by offerijns** [comment]
> So pallet-foreign-investments would need to furthermore take care of
> sending a ExecutedInvestOrder in this example back to the right domain

I think we should design `pallet-foreign-investments` as if it would also be used for linked pools, and thus it does not make sense to send these messages from `pallet-foreign-investments`. Rather I guess there should be hooks for executions from `pallet-foreign-investments` that `pallet-connectors` listens to and uses to send these messages.

**Comment by offerijns** [comment]
This comes back to this discussion: https://github.com/centrifuge/centrifuge-chain/pull/1364#discussion_r1236791220

I'm fine with implementing "Taking care of return messages and conenctors related bookeeping" either in a new `pallet-connectors-investments` or in `pallet-connectors`, but I don't think it makes sense to implement this in `pallet-foreign-investments

**Comment by NunoAlexandre** [comment]
Shall we find a moment to go through this discussion and fine tuning the spec together this week? 🏄‍♂️

**Comment by mustermeiszer** [comment]
Yes, definitely. I honestly do not care how the messages are triggered. I layed down my approach with the 3 invesments pallets. Lets have the sync about what needs to be there for this to work, how it is implemented can be decided by the implementer then.

**Comment by wischli** [comment]
Could you involve me as well in the call? Or at least, I would like to know if there is any more work required from my side for handling the `Executed*` messages.

**Comment by wischli** [comment]
Done by https://github.com/centrifuge/centrifuge-chain/pull/1473
