### ISSUE TITLE
Loans: Add slippage for settlement_price

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1464]
### Description

After merging https://github.com/centrifuge/centrifuge-chain/pull/1455 we leave a tech debt for the future of adding a `slippage` value to limit the values the borrower can choose regarding `settlement_price`. More in the [slack thread](https://centrifugedao.slack.com/archives/C05DX0RH1T3/p1688128534804769) about this.

It still requires a bit of design before implementing it

**Comment by lemunozm** [comment]
@offerijns, regarding this feature, the new `slippage` variable must set by the issuer when creating the loan in the `ExternalPricing, right? Or should it be something more global? Maybe per pool or so.

**Comment by offerijns** [comment]
I think we should initially add a per loan parameter now. Some assets could have very low slippage (as in, very liquid assets should be sold very close to the market price) vs other assets that could have more slippage, so it needs to be per asset.

In the future we could consider also adding a per pool parameter that is then basically a max slippage across assets, but I don't think this is necessary now.
