### ISSUE TITLE
Merge `fast-runtime` and `testnet-runtime` features

### ISSUE THREAD

**Issue by lemunozm** [centrifuge/centrifuge-chain#1468]
From @wischli:

> Why both features are not combined into just one?

I think the main reason is lazyness from our side as the `fast-runtime` is "inherited" from Substrate. It comes with macro support, i.e. `prod_or_fast!` for setting parameter types. 

IMO, we should merge both features. Additionally, **we have been building `fast-runtime` Altair WASMs over the past months even though there is NO use for them,** we only need it for Centrifuge runtime as our Catalyst test network runs with it. 

So most ideally, we should only have a `testnet-runtime` feature such that Altair@testnet-runtime is the Algol WASM and Centrigue@testnet-runtime is the Catalyst WASM.

_Originally posted by @wischli in https://github.com/centrifuge/centrifuge-chain/pull/1466#discussion_r1274834119_

**Comment by lemunozm** [comment]
It would imply changes in scripts to build the node. We should probably compile the development runtime with the `testnet-runtime` feature.

**Comment by wischli** [comment]
Closing due to the removal of `testnet-runtime` feature in #1587
