### ISSUE TITLE
Deploy block explorer: Polkascan

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/centrifuge-chain#149]

**Comment by emielvanderhoek** [comment]
Is the Amber testnet the best starting point for Polkascan?
lmk..

**Comment by philipstanislaus** [comment]
Hi @emielvanderhoek, yes, Amber would be the right one. Are you interested in contributing to this?

**Comment by emielvanderhoek** [comment]
Well, I built/designed Polkascan :) So I might be able to help...

**Comment by emielvanderhoek** [comment]
We built the client/node but there are no bootnodes configured. 
Could you provide met a list of bootnodes?

**Comment by philipstanislaus** [comment]
@emielvanderhoek happy to hear that! 

You can find all information on how to run a validator/node including bootnodes in our validator guide: https://centrifuge.hackmd.io/@pstehlik/rJ4ldDdiH

**Comment by emielvanderhoek** [comment]
Consider this issue closed.
https://polkascan.io/pre/centrifuge-amber

**Comment by philipstanislaus** [comment]
Awesome, thanks @emielvanderhoek !

**Comment by philipstanislaus** [comment]
@emielvanderhoek we started `Centrifuge Testnet Amber CC2` a few days ago, which replaces our previous testnet `Centrifuge Testnet Amber`. 

It would be great if you could also replace the testnet on Polkascan.

The guide has been updated accordingly: https://centrifuge.hackmd.io/@pstehlik/rJ4ldDdiH

**Comment by emielvanderhoek** [comment]
We already built the client. We are currently resolving some minor compatibility issues. We expect to have it up on polkascan.io next week.

**Comment by emielvanderhoek** [comment]
Done: https://polkascan.io/pre/centrifuge-amber-cc2

**Comment by philipstanislaus** [comment]
Awesome, thanks a lot!
