### ISSUE TITLE
[Altair] Mint treasury block rewards 

### ISSUE THREAD

**Issue by wischli** [centrifuge/centrifuge-chain#1495]
### Description

* Mint 3% p.a. block rewards into Altair Treasury instead of none
* Burn 15,752,730 AIR (equivalent of annual Treasury block rewards)
* MUST be part of the next release

### Research/based on

https://gov.centrifuge.io/t/rfc-altair-block-rewards-activation-and-treasury-burning-proposal/5503

### How will this affect the code base

* Less maintenance: Block rewards will then mirror between Altair and Centrifuge

### What are foreseen obstacles or hurdles to overcome?

* Burning of TBD: Probably handled in democracy, not in migration
* Align final numbers with DAO

**Comment by wischli** [comment]
Addition:

> AIR that are in the [modlcb/bridg](https://altair.subscan.io/account/kAKdGAcqfxWX23TwKtMUyobLEnDDzftMtJrfZppeUyLt5vs59) wallet, [should be burned] along with the portion that will burned from the Altair treasury, in an upcoming RU.
These tokens were airdropped back in July 2021 to the Centrifuge bridge wallet (all CFG holders received AIR in the ratio 1:1)

cc @Rhanok09 @ImdioR

**Comment by ImdioR** [comment]
Yes, sounds good!
