### ISSUE TITLE
GHA pipeline features

### ISSUE THREAD

**Issue by gpmayorga** [centrifuge/centrifuge-chain#1617]
### Description
Issue to define the pipeline enchancements we have discussed within the team that are "nice to have":
- [x] ~~Add `try_runtime` https://paritytech.github.io/try-runtime-cli/try_runtime/:~~
    ~~- When label `D8-migration` exists in PR~~
    ~~- Weekly on the main branch for sanity~~
   Solved by: #1735
- [x] Add code coverage to PR sanity checks (ideally per pallet).
   Solved by: #1745
   [ ] Pending: add integration tests to the tarpaulin code coverage, currently it hangs forever.
- [ ] Code scanning and security scanning (clippy, [miri](https://github.com/rust-lang/miri), [MIRAI](https://github.com/facebookexperimental/MIRAI)
- [ ] Test running srtool as a workflow container and setup sccache (the GHA cache is 2GB, too big)
- [ ] Post/upload srtool summary
- [ ] Review the Dockerfile again 
- [ ] Publish binary when release created
- [ ] Update the DockerHub Overview with a dynamic Readme file https://github.com/peter-evans/dockerhub-description
- [ ] Verifying all crates have proper Cargo features set via `subalfred`
- [ ]  (Optional) Add timing reports https://doc.rust-lang.org/nightly/cargo/reference/timings.html
- [ ] Fuzz testing?
- [ ] Ping Devs in Slack

### Research/based on

https://centrifuge.hackmd.io/Ftgot4ilSxK5ERyrEujnBg

**Comment by lemunozm** [comment]
Should this be closed?
