### ISSUE TITLE
Feat: On-chain Remarks

### ISSUE THREAD

**Issue by wischli** [centrifuge/centrifuge-chain#1647]
### Description

The goal is to allow issuers to connect an `Event::Remark(Remark)` to a Call so that it is known that the remark belongs to the executed call.

### Research/based on
* Spec: https://centrifuge.hackmd.io/FSjABNk2RSW3NNLq9vIINg

### How will this affect the code base

* Increases complexity and coupling of pallets

### What are foreseen obstacles or hurdles to overcome?

* Adds more (loose) coupling

**Comment by lemunozm** [comment]
What has changed with this feature? My last update was that finally we use the current remark infrastructure from substrate. After this issue: https://github.com/paritytech/substrate/issues/14727

**Comment by lemunozm** [comment]
cc @mustermeiszer
