### ISSUE TITLE
Cleanup: Remove `pallet-nft-sales`

### ISSUE THREAD

**Issue by wischli** [centrifuge/centrifuge-chain#1650]
### Description

* Remove `pallet-nft-sales` 
* Add migration to purge storage

### Research/based on

* Product roadmap by @mustermeiszer 

### How will this affect the code base

* Less code

### What are foreseen obstacles or hurdles to overcome?

* Migration required for purging storage

**Comment by lemunozm** [comment]
This is done https://github.com/centrifuge/centrifuge-chain/pull/1730
