### ISSUE TITLE
[LP v2] Feat: Add `Freeze` and `Unfreeze` messages to Liquidity Pools

### ISSUE THREAD

**Issue by wischli** [centrifuge/centrifuge-chain#1651]
### Description

Add two more outgoing LP messages which enable freezing and unfreezing an investor's address for a given pair of pool id and tranche id.

### Research/based on

* Product requirements by @hieronx and @mustermeiszer 
* https://centrifuge.hackmd.io/Soy4JiFbRSyovj53KW-a4A#Freeze

### How will this affect the code base

* Minor: Extends number of outgoing LP messages

### What are foreseen obstacles or hurdles to overcome?

* Must be tested on Demo before proposing RU to Centrifuge Chain

**Comment by mustermeiszer** [comment]
* No more token movements from that account

**Comment by wischli** [comment]
Closed via https://github.com/centrifuge/centrifuge-chain/pull/1947
