### ISSUE TITLE
Feat: Non-identical foreign investment swap rates

### ISSUE THREAD

**Issue by wischli** [centrifuge/centrifuge-chain#1654]
### Description

Right now, foreign investments only support 1-to-1 conversions for foreign and pool currencies via the `IdentityPoolCurrencyConverter` which impls `IdentityCurrencyConversion`. This MVP needs to be extended to support arbitrary conversion rates on a currency pair granularity.

### Research/based on

* WIP Spec: https://centrifuge.hackmd.io/oLZuEK7uSTuowQKpEjfVrw

### How will this affect the code base

* Increase complexity
* Touches `pallet-orderbook` and `pallet-foreign-investments` at the minimum

### What are foreseen obstacles or hurdles to overcome?

There are multiple codepaths in which `pallet-foreign-investments` needs to convert currency amounts from foreign to pool and vice versa because any foreign LP message amount is always denominated in the foreign currency. E.g., when an investor mutates their investment or they receive a message of their mutated investment amounts. We need to make sure accuracy is still intact.

#### Specific code paths

- [ ] https://github.com/centrifuge/centrifuge-chain/blob/6535d758e74b648124297d75cfdfa36f518c5987/pallets/liquidity-pools/src/lib.rs#L462-L464

**Comment by mustermeiszer** [comment]
@lemunozm this should be part of the new logic where pallet-order-book swaps with non 1:1 conversion

**Comment by wischli** [comment]
Closed by #1674
