### ISSUE TITLE
Feat: Linear Accrual on Settlement Price

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#1738]
### Description
Currently, when we are using the `ExternalPricing` we are allowing the `last_settlement_price` to be used as a base for valuation in cases where there is no oracle, or the oracle itself is outdated. 

As an intermediate step between the current logic and [loans v4](https://centrifuge.hackmd.io/1OXnuqyBRIuZK9iNozuFvA?view) the goal is to have an estimate of the value of an asset based on the `settlement_price`, `time_till_maturity` and the `notinal`. 

See calculation example for formula: 
![image (3)](https://github.com/centrifuge/centrifuge-chain/assets/28841470/20ea916d-2536-416b-aef0-49217f0cf426)

### Research/based on
* Issuer needs to update asset price valuations without needing to submit oracles continuously

### How will this affect the code base
* Increase complexity

### What are foreseen obstacles or hurdles to overcome?
* Migration of loans needed (*probably*) IF we need to store the last time updated. But I think we can get around that by just calculating the value dynamically and not iteratively

**Comment by lemunozm** [comment]
> But I think we can get around that by just calculating the value dynamically and not iteratively

Could you extend this? How we can get rid of storing the last time settlement price was updated

**Comment by mustermeiszer** [comment]
Mmmh. I thought we could use the creation date of the loans.

**Comment by lemunozm** [comment]
The problem with that is that the creation date of the loan is different from the moment a settlement price is set.
