### ISSUE TITLE
`Registries` storage

### ISSUE THREAD

**Issue by vlopes11** [centrifuge/centrifuge-chain#251]
* Create a structure `Registry` with the following attributes

- `controllers`: array of `AccountId`
Set of accounts with permission to mint a NFT into the registry or update its data

- `allow_burn_by_owner`: boolean
If true, the owner of a NFT will also be allowed to call the method `burn` for it.
If false, the method `burn` will allow only the controllers of the registry to burn a given NFT.

- `data_validator`: `[u8]`
Optional extra data containing the minimum required fields that should be present on a NFT mint. Will be validated only if called from the service instance `AttributeVerifier::mint` that is to be implemented on the chain side.

* Create a storage that maps a `RegistryId => Registry`

It should implement the trait `frame_support::storage::StorageMap`

This is an example of the default implementation:
```
decl_storage! {
    trait Store for Module<T: Trait> as Registries {
        pub RegistryById: map T::Hash => Registry;
    }
}
```

This storage should also implement the following methods:

- `create_registry(controllers, allow_burn_by_owner) -> registry_id`
Append the provided parameters to the `Registries` and returns its id

- `mint(registry_id, account_id, token_id, data)`
Will validate if `account_id` belongs to `Registry::controllers`. If yes, will include the map `token_id => data` into `NFT` storage.

- `burn(registry_id, token_id, depositor)`
Will validate if the requester is the owner of the NFT. If yes, will burn the NFT. The deposit will be refunded to the NFT owner.

Externd from:
https://github.com/centrifuge/substrate-pallet-nft-registry/blob/master/src/erc721/mod.rs

**Comment by lucasvo** [comment]
> data_validator: Optional extra data containing the minimum required fields that should be present on a NFT mint. Will be validated only if called from the service instance AttributeVerifier::mint that is to be implemented on the chain side.
Why is this part of the registry and not the attribute verifier?
