### ISSUE TITLE
Build seems to fail on new Ubuntu baremetal

### ISSUE THREAD

**Issue by lukesaunders** [centrifuge/centrifuge-chain#252]
```
   Compiling parity-scale-codec v1.1.2
   Compiling impl-codec v0.4.2
   Compiling sp-arithmetic v2.0.0 (/root/.cargo/git/checkouts/substrate-7e08433d4c370a21/ddb309a/primitives/arithmetic)
   Compiling primitive-types v0.6.2
error: this operation will panic at runtime
   --> /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/ddb309a/primitives/arithmetic/src/fixed64.rs:149:32
    |
149 |             return Fixed64::from_parts( self.0 / zero);
    |                                         ^^^^^^^^^^^^^ attempt to divide by zero
    |
    = note: `#[deny(unconditional_panic)]` on by default

error: aborting due to previous error

error: could not compile `sp-arithmetic`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Operating system:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

Following commands from here https://developer.centrifuge.io/chain/get-started/run-node/ for Amber chain (I also tried Flint which resulted in the same error).

Edit: [Googling](https://www.reddit.com/r/substrate/comments/ggzp1v/need_some_help_to_install_substrate/) suggests a different Substrate version could help, but this doesn't seem in my control.

**Comment by mikiquantum** [comment]
@lukesaunders Can you try using the latest release https://github.com/centrifuge/centrifuge-chain/releases/tag/v1.1.0 ?
I believe the release versions on the docs are outdated. Will update asap.
Let us know if that works.

**Comment by lukesaunders** [comment]
@mikiquantum yep that builds fine, thanks. I've replied on Slack and I think this can be closed now or after the docs are updated.

**Comment by mikiquantum** [comment]
Thanks, closing now, docs updated.
