### ISSUE TITLE
Node doesn't sync 

### ISSUE THREAD

**Issue by AlexZhenWang** [centrifuge/centrifuge-chain#269]
Hi guys, I am trying to run a node on local to connect to centrifuge mainnet, but from the log, seems like the node is not syncing. Did I do anything wrong?

The way I run the node 
`docker run -it --rm --entrypoint /usr/local/bin/centrifuge-chain centrifugeio/centrifuge-chain:latest`

The log:
![image](https://user-images.githubusercontent.com/14008461/92201045-8e399200-eecf-11ea-9eef-a79f96bcc5da.png)

**Comment by vedhavyas** [comment]
Did you compile the binary from Master? If so, we are in the middle of a migration and Node will not be able to sync directly ATM.

If you want to run a Node, use the existing releases to build your Binary. Those should work as expected.

You would also need to start the node with Bootstrap nodes to connect to other peers. You can find them all here - https://developer.centrifuge.io/chain/get-started/run-node/

Please re-open the ticket if not solved

**Comment by AlexZhenWang** [comment]
Hi @vedhavyas, thank you so much for checking this for me!

I tried to run the command in doc,
![image](https://user-images.githubusercontent.com/14008461/92325115-2edcad00-f09c-11ea-8997-a927fe434a47.png)

it worked for me.

But when I tried to run the [latest version ](https://hub.docker.com/r/centrifugeio/centrifuge-chain/tags)
![image](https://user-images.githubusercontent.com/14008461/92325128-43b94080-f09c-11ea-9e20-fc38b6cc8334.png)

with the bootnodes showing in doc, the node doesn't sync.

Seems like the bootnodes in doc
```
--bootnodes=/ip4/35.242.220.32/tcp/30333/p2p/QmNeEcU7pfcvqYHJhakBvZsAndd2o1wLecpiu5kSDXebSW     --bootnodes=/ip4/34.89.236.50/tcp/30333/p2p/Qma8avu1Cwhiynk6vUv5e1vK5LV7zzmLsoaVEd7La4ju8D
```
is for version `20200506231744-908086f` but not the latest version `20200902143144-9923181`.
Should I use the version `20200506231744-908086f` that is showing in the doc? Or should I use the latest version but with some other bootnodes?

The command I was using to run the latest version is 
```
docker run -p 30333:30333 -p 9933:9933 -p 9944:9944 --rm -it centrifugeio/centrifuge-chain:20200902143144-9923181 centrifuge-chain   --chain=mainnet     --bootnodes=/ip4/35.242.220.32/tcp/30333/p2p/QmNeEcU7pfcvqYHJhakBvZsAndd2o1wLecpiu5kSDXebSW      --bootnodes=/ip4/34.89.236.50/tcp/30333/p2p/Qma8avu1Cwhiynk6vUv5e1vK5LV7zzmLsoaVEd7La4ju8D
```
please let me know if there is anything I did was wrong, thank you!

**Comment by vedhavyas** [comment]
@AlexZhenWang yes they wouldn't sync with latest version because the sync protocol changed in the latest version. We are doing the migration for this ATM. Give us sometime with the latest version.

If you want to sync with testnets but not latest version, please use the latest release to build your node. That should sync fine with all the testnets and mainnet as well
