### ISSUE TITLE
When building centrifuge-chain with a nix-flake the commit id is not set

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/centrifuge-chain#300]
This is not functioning properly: https://github.com/paritytech/substrate/blob/2e34d473e6ba81b454eb039544f2162975c0b30b/utils/build-script-utils/src/version.rs#L22

**Comment by asymmetric** [comment]
Can confirm: https://github.com/centrifuge/centrifuge-chain/runs/2245034171?check_suite_focus=true#step:5:542

**Comment by mustermeiszer** [comment]
@mikiquantum still relevant? if yes, feel free to re-open.
