### ISSUE TITLE
Implement Reward-Pallet for Crowdloan Capabilities 

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#317]
**AS A** `Contributor` participating in a Polkadot/Kusama [parachain](https://wiki.polkadot.network/docs/en/learn-parachains) [crowdloan](https://wiki.polkadot.network/docs/en/learn-crowdloans) `Campaign`
**I WOULD LIKE TO** be rewarded in parachain's native tokens
**SO THAT TO** compensate for the **forgoing stacking** of the tokens that I blocked on the Polkadot/Kusama [relay chain](https://wiki.polkadot.network/docs/en/learn-architecture#relay-chain), for the term of the `Campaign`.

## Acceptance criteria
- [x] To invest in a crowdloan (or community-backed funding), a `Contributor` (or `Investor`) MUST lock tokens on Polkadot/Kusama [relay chain](https://wiki.polkadot.network/docs/en/learn-architecture#relay-chain) (i.e. DOT or KSM, respectively), hence *forgoing staking*.
- [x] For a `Contributor` to claim a reward payout, the `Campaign` MUST be first closed successfully. 
- [x] A`Contributor` MUST prove her/his identity to the parachain before being eligible for reward payouts.
- [x] The `Reward Module` MUST allow for custom rewarding mechanism (e.g. upfront payment, vesting, ...)
- [x] The `Reward Module` MUST be compatible with Polkadot and Kusama ecosystems.

## Risks
None

## References
[**Crowdloan Technical Specification**](https://centrifuge.hackmd.io/JIGbo97DSiCPFnBFN62aTQ#contributor-identity)
[**Crowdloan Reward Mechanism**](https://centrifuge.hackmd.io/NPmnf3a2R3SAN75nA-QSRw)

**Comment by mustermeiszer** [comment]
@tankofzion would you close this, or do you want to keep it open, as long as you are on the testing side?

**Comment by mikiquantum** [comment]
done
