### ISSUE TITLE
Implement Claim-Pallet for Crowdloan Capabilities

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#319]
**AS** a `Contributor` investing in a Polkadot/Kusama [`Crowdloan Campaign`](https://wiki.polkadot.network/docs/en/learn-crowdloans)
**I WOULD LIKE** to claim a reward payout
**SO THAT** to be rewarded for the tokens I locked on the Polkadot/Kusama [relay chain](https://wiki.polkadot.network/docs/en/learn-architecture#relay-chain) during the [`Crowdloan Campaign`](https://wiki.polkadot.network/docs/en/learn-crowdloans).

## Acceptance criteria
- [x] In order to invest in a [`Crowdloan Campaign`](https://wiki.polkadot.network/docs/en/learn-crowdloans) (or community-backed funding), a `Contributor` MUST lock tokens on Polkadot/Kusama [relay chain](https://wiki.polkadot.network/docs/en/learn-architecture#relay-chain) (i.e. DOT or KSM, respectively), hence **forgoing staking**.
- [x] The `Contributor` MAY receive a reward payout on the [parachain](https://wiki.polkadot.network/docs/en/learn-parachains), as a compensation for forgoing staking.
- [x] The `Claim Module` DOES NOT implement the rewarding strategy or mechanism. This is the role of the `Reward Module`(see  §4.3 Claim Module Description, in the  [**Crowdloan Technical Specification**](https://centrifuge.hackmd.io/JIGbo97DSiCPFnBFN62aTQ#43-Claim-Module-Description) for more technical information and the story #317 for `Reward Module` implementation).
- [x] For a `Contributor` to be able to claim a reward payout, the `Crowdloan Campaign` MUST be closed successfully. 
- [x] For a `Contributor` to be eligible for a reward payout, she/he MUST prove her/his identity to the [parachain](https://wiki.polkadot.network/docs/en/learn-parachains), as well as the amount of her/his contribution (i.e. how many tokens she/he locked on her/his relay chain account).
- [x] For a `Contributor` to be rewarded on the parachain, she/he MUST provide the `Claim Module` with a [parachain](https://wiki.polkadot.network/docs/en/learn-parachains) account address.
- [x] The `Reward Module` MUST implement a mechanism for preventing potential [replay attacks](https://en.wikipedia.org/wiki/Replay_attack) (i.e. the `Contributor` claiming twice or more a reward payout). This is not the responsibility of the `Claim Module` implemented in this story.

## Related stories:
#317 

## Risks
- [x] Low: The messaging between the relay chain and the parachain (or XCM messages).

## References
[**Crowdloan Technical Specification**](https://centrifuge.hackmd.io/JIGbo97DSiCPFnBFN62aTQ)
[**Crowdloan Reward Mechanism**](https://centrifuge.hackmd.io/NPmnf3a2R3SAN75nA-QSRw)

**Comment by mustermeiszer** [comment]
@tankofzion would you close this, or do you want to keep it open, as long as you are on the testing side?

**Comment by mikiquantum** [comment]
done
