### ISSUE TITLE
Convert Standalone Centrifuge Chain to Parachain

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#326]
Acceptance criteria:
- [ ] Adapt runtime and service to Cumulus (this involves all dependencies to same substrate/polkadot/cumulus versions)
- [ ] Adjust all deployment scripts and templates
- [ ] Deploy to Charcoal (testnet connected to Rococo & Chachacha)
- [ ] Implement Collator rewards & staking
- [ ] XCMP configured and supporting xtokens pallet

**Comment by wischli** [comment]
Is this still relevant or can we close?

**Comment by mikiquantum** [comment]
Yes, closing now.
