### ISSUE TITLE
Define migration strategy plan

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#335]
Research on what Parity suggests as the best strategy for standalone chains to migrate to become parachains. 
Tailor those said best practices to our own chain.

**Comment by mustermeiszer** [comment]
As an update our current approach is defined here in detail: https://centrifuge.hackmd.io/XWWiHoIEQLSF1sOme3yWvg?both

**Comment by mikiquantum** [comment]
done
