### ISSUE TITLE
Altair shell

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/centrifuge-chain#386]
Cleanup and update the runtime with the Shell for Altair

**Comment by branan** [comment]
My general thought on how we'd want to do this:

* Rename the current runtime to charcoal-runtime (runtime/charcoal)
* Add altair-runtime as a shell (runtime/altair)

Then the work to move charcoal-runtime into runtime-common, creating a real altair runtime based on runtime-common, and removing charcoal-runtime, can be done in a future ticket.

**Comment by vedhavyas** [comment]
I would be easier to just replace current runtime with altair.
Future tickets will take add more sugar around the multiple runtimes such as CFG runtime along side the altair. This way, we can be ready for westmint and other altair based testnets much faster.

Also note that current pallet v2 migration is happening in parallel. better to not step on marc's work there. 

Do you see any concerns with this approach ?

**Comment by branan** [comment]
I guess my main concern was to be sure we don't block any development work that needs to be tested on Charcoal (until we fully transition Charcoal to running test builds of the Altair runtime). As long as we're happy running Charcoal off of a different branch for now it all should be fine?

**Comment by vedhavyas** [comment]
I will have draft PR in sometime and will also include the details in a HackMD for us to go through in sync tomorrow
