### ISSUE TITLE
Add release action in Ci

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/centrifuge-chain#400]
The releasee action should do the following on push of a git tag:
- Run build-node and build-runtime
- Zip/tar node binary with OS name
- Push to RPM repository
- Build docker images by installing centrifuge-chain RPM
- Upload tar/zip, runtime wasm from the build runtime and its log file
- pull down those assets in release job
- extract srtool final output from the log
- Generate the changelog between releases and append srtool log
- Create a Github draft release with Binary and WASM assets, and changelog txt as notes

Here is an example from go-centrifuge node - https://github.com/centrifuge/go-centrifuge/blob/develop/.github/workflows/release.yml

Polkadot release - https://github.com/paritytech/polkadot/blob/master/.github/workflows/publish-draft-release.yml

**Comment by mustermeiszer** [comment]
@mikiquantum still relevant?

**Comment by mikiquantum** [comment]
We will soon need a flavor of this issue, for now we can close and open a new one with slightly different requirements.
