### ISSUE TITLE
Implement script for state extraction

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#405]
The current script is a local script on my side. Possibly move this into @tankofzion cli or move into a small standalone script, which lives in some repo.

**Comment by mustermeiszer** [comment]
Script lies here: https://github.com/centrifuge/centrifuge-cli-chain/tree/master/src

**Comment by tankofzion** [comment]
Great :) Tks Freddy. We shall open a ‘packages’ folder in 'centrifuge-cli-core’ for our ‘core’ commands. So that we keep centrifuge-cli repo lean. And then we shall split the ‘centrifuge-cli-core’ later (if necessary).

**Comment by mustermeiszer** [comment]
This is closed with the updated CLI here: https://github.com/centrifuge/centrifuge-cli
