### ISSUE TITLE
Some example about how to create a document

### ISSUE THREAD

**Issue by DiazRock** [centrifuge/centrifuge-chain#445]
I'm following the official doc of the [node API](https://centrifuge-os-node-api-7.api-docs.io/2.0.0), and the [developers docs](https://docs.centrifuge.io/build/p2p-node/) for a p2p node. I succes installed my node on my machine with ubuntu 18.04. I ping it and I got:

```json
{
    "version": "1.0.0+0b1c3d55df5c410a5a6c57a1addcfa2c26b0a58f",
    "network": "flint"
}
```
 I want to create a document with my centrifuge node. But I can't find any example around there, and the example of api docs is not very helpful. I tried with this json 
```json
{
    "attributes": {},
    "data": {},
    "document_id": "",
    "read_access": [
        "string"
    ],
    "schema": "",
    "write_access": [
        "string"
    ]
}
```
But it gave me "Malformed address". I tried generating two bit32 numbers in hex format for `schema` and `document_id`, but I got the same error. Would you guys help me?

**Comment by vedhavyas** [comment]
@DiazRock please open an issue on https://github.com/centrifuge/go-centrifuge
That where node issues are tracked. Thanks!
