### ISSUE TITLE
Bridge should not use `free_balance` for transfer

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/centrifuge-chain#450]
Bridge should not use `free_balance` for checking if the account has enough funds for bridge fees and the amount to be transferred combined. Instead `usable_balance` with Misc and Fee, which ever is minimum should be used to check the sufficient balance check. If not, in some cases, bridge will end up burning 200cfg first and fails when actual amount is being transferred since there wont be sufficient usable funds to transfer.

Also, bridge extrinsics should always use `transactional` macro for rolling back the changes.

**Comment by mikiquantum** [comment]
done
