### ISSUE TITLE
Implement Datadog support for collecting and filtering logs from VMs and containers

### ISSUE THREAD

**Issue by tankofzion** [centrifuge/centrifuge-chain#503]
## Objectives
- [x] Implement logs filtering pipelines and processors (using Terraform scripts) for Datadog, so that to avoid incorrect log mappings (a warning being tagged as error or inversely, for instance)
- [ ] Deploying Datadog agent on GCE VMs (i.e. by modifying VM image and/or installing Datadog agent after the VM is provisioned).

**Comment by mustermeiszer** [comment]
@tankofzion and @mikiquantum what is the state of this?

**Comment by mustermeiszer** [comment]
I will close this. In case anybody this needs this @mikiquantum, please re-open.
