### ISSUE TITLE
Version Local Pallets in Runtimes

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#511]
In order to not accidently introduce breaking changes when changing one off our own pallets it might be beneficially to release versions of the pallets to crates.io and use this versions instead of links to the branch. 

- [ ] Research benefits and downsides of this approach
- [ ] Research possible alternatives
- [ ] Implement a bot/or workflow to ease releasing

**Comment by mikiquantum** [comment]
Not clear yet, closing for now
