### ISSUE TITLE
Design a custom collator whitelisting pallet

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#530]
Right now, we run a PoA setup where our validators/collators are listed in genesis and selected through the session pallet to go on producing blocks.

We want to build a pallet that allows us to whitelist specific collator candidates so that we can, also through this pallet, implement a custom `ValidatorRegistration` impl that checks both for our whitelisting flag as well as for the default `Session` impl of said trait.

Worth noting that this is not meant to be our long-term approach to collator selection but rather a temporary solution that allow us to have more control over the selected collators until we have picked the right staking solution for us, and to avoid a FCFS setup.

We can break this work in small deliverable PRs

- [x] 1. Implement and test the pallet itself with the expected use cases and requirements (https://github.com/centrifuge/centrifuge-chain/pull/535)
- [x] 2. Add benchmarks and auto-generate the right weights + add the pallet to the altair and development runtimes (https://github.com/centrifuge/centrifuge-chain/pull/542)

**Comment by NunoAlexandre** [comment]
@mustermeiszer regarding (*A), if I got it right, this extrinsic is a sudo-only call. 

Could you also point me to the right labels I should add to this issue pls?

**Comment by mustermeiszer** [comment]
@NunoAlexandre can you base your work upon https://github.com/centrifuge/centrifuge-chain/tree/rt4?

**Comment by NunoAlexandre** [comment]
Done ✅
