### ISSUE TITLE
Implement Tinlake rewards migration script

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#579]
### Objectives

This task aims at implementing a command for Centrifuge [Commander](https://github.com/centrifuge/commander), for transferring Tinlake reward claims from the standalone Centrifuge chain to a Centrifuge parachain (or collator node)
This command will be executed while the standalone chain will be stopped (i.e. no more producing blocks).
Consequently, the latest block which invoked the `radClaims.storeRootHash(root_hash)` transaction on standalone (or source) Centrifuge chain's [`pallet_claims`](https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/claims/src/lib.rs#L407) pallet will be used to extract the 
latest [`RootHashes`](https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/claims/src/lib.rs#L251) storage item of this (`pallet_claims`) pallet.

### Overview
Since the way that we currently check if an account has already claimed involved storing a map of account and balance claimed, we would need to move this storage to the new chain.
Doing a quick research, there are 330 entries on the claimed storage. And around 870 root hashes entries.

### Approach Suggested

- Export all Claimed and RootHash Storage into a file
- Parse this file into individual scale encoded k/v entries in form of a list (items)
- Make use of Sudo call for System.setStorage(items):

Open questions:
- Can we clean up the roothash list (extract rewards that have already been  claimed)?

### Tasks

[ ] **Extract root hash** - Implement a new command for Centrifuge [Commander](https://github.com/centrifuge/commander), for extracting the root hash (containing reward claims) from the latest block which invoked `radClaims.storeRootHash(root_hash)` transaction on Centrifuge chain, and to migrate this root hash to the target parachain. The number of this latest block will be given when invoking the migration command, extracted from Subscan, for instance, as soon as the Centrifuge chain will be stopped. The command usage will be (here with a local collator node as parachain's Websocket endpoint):
`centrifuge claims migrate --from wss://fullnode-archive.centrifuge.io --to ws://localhost:9944 --block 9552601`

[ ] **State testing routines** - Implement a bunch of tests for checking the storage state on the parachain.

### References

- Specification: https://centrifuge.hackmd.io/HpGW0J6TRo25splXkuH9TA?both#5-Tinlake-Rewards-Migration
- Related source code: https://github.com/centrifuge/cfg-claims-admin/blob/main/src/index.ts#L119 -> https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/claims/src/lib.rs#L406

**Comment by NunoAlexandre** [comment]
@mikiquantum regarding your **Approach suggestion** above, could you explain why the suggestion to store the items to a file before parsing VS parsing everything in memory in one go? Just curious.

**Comment by mikiquantum** [comment]
@NunoAlexandre no need to use a file, it can be done in memory as long as we execute a verification check at the end.

**Comment by NunoAlexandre** [comment]
Done in https://github.com/centrifuge/centrifuge-cli/pull/25
