### ISSUE TITLE
Anchor: Add worker to evict expired pre-commits

### ISSUE THREAD

**Issue by pstehlik** [centrifuge/centrifuge-chain#58]
As the upgrade to Substrate 2.0 (master branch) is done, we can now add the worker to evict expired pre-commits.

Additional reading:
* Discussion with todr - https://centrifuge.hackmd.io/dxSQCYK6TUi8gy4M_76-9Q
* Im online module https://github.com/paritytech/substrate/blob/646b54cb0d35b0ec8d921998b259fce6ca77f8be/srml/im-online/src/lib.rs#L406

**Comment by mustermeiszer** [comment]
closed due to stalled.
