### ISSUE TITLE
Limit number of tranches

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#590]
We should investigate the limit a bit more, and then we should limit the number of tranches. Was actually planning to tackle it in this PR but didn't get to it yet, will create a ticket for it.

_Originally posted by @offerijns in https://github.com/centrifuge/centrifuge-chain/pull/588#discussion_r785850608_

**Comment by branan** [comment]
Whatever number we want for this limit is required for benchmarking
