### ISSUE TITLE
Investigate Potential Bug Investments Solely into Senior Tranche

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#615]
In a test case we found that one could solely invest into a senior tranche directly after start of a pool. This lead to all the yields going into the senior tranche. 

Maybe the test-case was wrong or the there is a bug. 

# Notes:
* Setup Pool:
  ```
  /// * 5 Tranches
  ///     * 0: 3% APR, 25% Risk buffer, Seniority 5
  ///     * 1: 5% APR, 10% Risk buffer, Seniority 4
  ///     * 2: 7% APR, 5% Risk buffer, Seniority 2
  ///     * 3: 10% APR, 5% Risk buffer, Seniority 1
  ///     * 4: Junior Tranche
  ```
* Investments: 2 x 500 into tranche 0
* Setup Loan:
  ```
   APR: 15%
   ADVR: 90%
   DR: 4%
   Amount: 1000
  ```
* Borrow 900
* 20 days passed
* Tranche token prices afterwards:
    ```
    tranche 0: 2.064
    tranche 1: 1.0
    tranche 2: 1.0
    tranche 3: 1.0
    tranche 4: 1.0
    ```

**Comment by branan** [comment]
Did the test case not get updated for the tranche re-ordering? Tranche 0 is supposed to be the junior tranche now. This behavior would be consistent with that

**Comment by mustermeiszer** [comment]
This is not possible. So will close it.
