### ISSUE TITLE
Pallet-pools/collect: Error out instead of implicit using `last_epoch_closed`

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#618]
Instead of the current behaviour, where we chose `min(order.epoch + collect_n_epoch, pool.last_epoch_executed)` we want to error out if the `order.epoch + collect_n_epoch` ranges beyond the last executed epoch.

**Comment by branan** [comment]
Why error here?

In theory we'd want the `collect` extrinsic to just collect everything. We need some `n` for our weight function, so we take a parameter to bound the collection. The point of that parameter is solely to set a bound for the weight, so it's fine if it's above what is actually required. The extrinsic will refund the weight difference in the end.

**Comment by mustermeiszer** [comment]
Yes, but this implicit behaviour is not good in the backend. At least from my point of view. We will have an extrinsic in storage that does collect `n` epochs and is successful and we have an event that signals `min(n, last_epoch_executed)`. The front-end will take care of bounding a user to only valid inputs, but from my point of view, the chain should only accept valid inputs and not make any implicit behaviour.

**Comment by mustermeiszer** [comment]
> In theory we'd want the collect extrinsic to just collect everything. We need some n for our weight function, so we take a parameter to bound the collection. The point of that parameter is solely to set a bound for the weight, so it's fine if it's above what is actually required. The extrinsic will refund the weight difference in the end.

Although, upon second thought. If we wanna keep the existing approach I would suggest, we remove the parameter `collect_n_epochs` and use an associated type `MaxCollectEpochs` or something and use this as an upper bound what one can collect in a single collect call? WDYT? 

I thought at the beginning that we wanted to have the ability to collect especially user defined n-epochs. But if it should be an overall just collect, I think the current solution with the upper bound would be a goog middleground.
