### ISSUE TITLE
PRTU3 - Add Crowdloan Claim Pallets 

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/centrifuge-chain#627]
This Upgrade enabled Crowdloan Claiming.

Since after the snapshot the network will be populated and access to CFG is easier, we should remove the unsigned extrinsic logic and let the sender pay for the fees. Of course sender can still claim on behalf of anyone else as long as can verify its identity as before.

**Comment by NunoAlexandre** [comment]
Closed by https://github.com/centrifuge/centrifuge-chain/pull/769
