### ISSUE TITLE
Parity Signer support

### ISSUE THREAD

**Issue by Slesarew** [centrifuge/centrifuge-chain#630]
To become compatible with Parity Signer now, Centrifuge should either:

a. Update metadata version to at least v12 AND add all missing types to Signer's [legacy types definitions file](https://github.com/paritytech/parity-signer/blob/master/rust/defaults/default_types/full_types_information) 

OR

b. Update metadata version to at least v14

After that, as a convenience for users, signed network addition and metadata updates might be hosted somewhere. Either contact maintainers of [Parity metadata portal](https://metadata.parity.io/) to use their certificate or issue your own; preferably both. [Certificates are temporary measure](https://github.com/paritytech/parity-signer/issues/898) until chains are made to [check metadata validity in trustless way](https://github.com/paritytech/substrate/issues/10478).

All this is needed for offline transaction parsing and display. I'm leaving this ticket here because Signer's users asked about support in Signer's repo https://github.com/paritytech/parity-signer/issues/927.

**Comment by mustermeiszer** [comment]
@Slesarew We will phase out the current stand-alone chain of Centrifuge in favor of the Parachain that will be onboarded in march to polkadot. The parachain will of course support latest metadata. I am closing this therefore. If there are any questions left or my answer doesn`t solve the problem, feel free to comment again.
