### ISSUE TITLE
Refactor `LoanValueInvalid` error

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#643]
`LoanValueInvalid` is probably most common error, as the input for the `loans.price()` is complex. This complexity will grow as we add more loan types.

We can either separate it, or wait until https://github.com/paritytech/substrate/pull/10242 is released and add a field to the error.

**Comment by branan** [comment]
I think because the LoanType has logic around validity (admittedly pretty minimal right now, but that could change with future loan types) we're better off manually setting up our error handling here

**Comment by mustermeiszer** [comment]
As parity merged this, we should go with something like `LoanValueInvalid { reason: InnerLoanError }` or something.
