### ISSUE TITLE
Allow querying NFT sale listings by account

### ISSUE THREAD

**Issue by onnovisser** [centrifuge/centrifuge-chain#662]
The NFT Studio has an Account page where a user can see the NFTs that they own. When listing an NFT for sale, its ownership is transferred (to the nftSales pallet I presume). This means the NFT won't be returned anymore when querying `uniques.account()` for an address, but we'd still like to display these NFTs on the account page. The only way to get these NFTs at the moment would be to query all listings across all collections and then filter them by address, but this is a potentially inordinate amount. If possible, allow querying NFT sale listings by account, similar to `uniques.account()`.

**Comment by NunoAlexandre** [comment]
@onnovisser would having a query with the following signature suffice all your needs?

``` 
query(seller_account) -> Vec<(class_id, instance_id)>
```

**Comment by onnovisser** [comment]
Yes, would be perfect.
