### ISSUE TITLE
target chain reported a "AssetIdConversionFailed" error

### ISSUE THREAD

**Issue by 99Kies** [centrifuge/centrifuge-chain#666]
Hello, I would like to ask about the configuration under Trader. When I send a cross-chain asset transfer, the target chain reported a "TooExpensive" error.
this is my operation: chainA -> [chainA_native_token] -> chainB

https://github.com/centrifuge/centrifuge-chain/blob/parachain/runtime/development/src/lib.rs#L1244

![image](https://user-images.githubusercontent.com/45918704/156310907-c37b6958-1c7d-40f5-8f14-1d64c6ebe70f.png)

**Comment by mustermeiszer** [comment]
@NunoAlexandre Do you know the issue? ^^

**Comment by NunoAlexandre** [comment]
@99Kies can you describe what you are trying to achieve and what the local environment you are setting up to run these calls looks like?

**Comment by 99Kies** [comment]
https://github.com/centrifuge/centrifuge-chain/blob/parachain/runtime/development/src/lib.rs#L1244
https://github.com/paritytech/polkadot/blob/cc24fb87b702db6510d08c689e442b6be384d798/xcm/xcm-executor/src/traits/weight.rs#L78

**Comment by 99Kies** [comment]
Here are my transaction parameters:
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/45918704/156346320-b1852219-de1e-4c94-903a-4bbd898f10cd.png">
and this my Trader config:
```rust
pub type Trader = (
    FixedRateOfFungible<RocPerSecond, ()>,
    FixedRateOfFungible<NativePerSecond, ()>,
    FixedRateOfFungible<NativeNewPerSecond, ()>,
    FixedRateOfFungible<FfPerSecond, ()>,
);

parameter_types! {
	pub RocPerSecond: (AssetId, u128) = (MultiLocation::parent().into(), roc_per_second());
	pub NativePerSecond: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(2000), GeneralKey(CurrencyId::DORA.encode()))
		).into(),
		10_000
	);
	pub NativeNewPerSecond: (AssetId, u128) = (
		MultiLocation::new(
			0,
			X1(GeneralKey(CurrencyId::DORA.encode()))
		).into(),
		10_000
	);

	pub FfPerSecond: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(1000), GeneralKey(CurrencyId::FF.encode()))
		).into(),
		200_000
	);
}
```

**Comment by NunoAlexandre** [comment]
@99Kies what is the parachain id of the sending parachain?

**Comment by 99Kies** [comment]
> @99Kies what is the parachain id of the sender parachain?

is `1000`
parachainA 1000
parachainB 2000

**Comment by 99Kies** [comment]
> Here are my transaction parameters: <img alt="image" width="1465" src="https://user-images.githubusercontent.com/45918704/156346320-b1852219-de1e-4c94-903a-4bbd898f10cd.png"> and this my Trader config:
> 
> ```rust
> pub type Trader = (
>     FixedRateOfFungible<RocPerSecond, ()>,
>     FixedRateOfFungible<NativePerSecond, ()>,
>     FixedRateOfFungible<NativeNewPerSecond, ()>,
>     FixedRateOfFungible<FfPerSecond, ()>,
> );
> 
> parameter_types! {
> 	pub RocPerSecond: (AssetId, u128) = (MultiLocation::parent().into(), roc_per_second());
> 	pub NativePerSecond: (AssetId, u128) = (
> 		MultiLocation::new(
> 			1,
> 			X2(Parachain(2000), GeneralKey(CurrencyId::DORA.encode()))
> 		).into(),
> 		10_000
> 	);
> 	pub NativeNewPerSecond: (AssetId, u128) = (
> 		MultiLocation::new(
> 			0,
> 			X1(GeneralKey(CurrencyId::DORA.encode()))
> 		).into(),
> 		10_000
> 	);
> 
> 	pub FfPerSecond: (AssetId, u128) = (
> 		MultiLocation::new(
> 			1,
> 			X2(Parachain(1000), GeneralKey(CurrencyId::FF.encode()))
> 		).into(),
> 		200_000
> 	);
> }
> ```

this config is parachainB XcmConfig::Trader config.

**Comment by 99Kies** [comment]
this is my parachainA XcmConfig::Trader config:
```rust
pub type Trader = (
	FixedRateOfFungible<RocPerSecond, ()>,
	FixedRateOfFungible<NativePerSecond, ()>,
	FixedRateOfFungible<NativeNewPerSecond, ()>,
	FixedRateOfFungible<DoraPerSecond, ()>,
);

parameter_types! {
	pub RocPerSecond: (AssetId, u128) = (MultiLocation::parent().into(), roc_per_second());
	pub NativePerSecond: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(1000), GeneralKey(CurrencyId::FF.encode()))
		).into(),
		roc_per_second() * 80
	);
	pub NativeNewPerSecond: (AssetId, u128) = (
		MultiLocation::new(
			0,
			X1(GeneralKey(CurrencyId::FF.encode()))
		).into(),
		roc_per_second() * 80
	);

	pub DoraPerSecond: (AssetId, u128) = (
		MultiLocation::new(
			1,
			X2(Parachain(2000), GeneralKey(CurrencyId::DORA.encode()))
		).into(),
		roc_per_second() * 100
	);
}
```

**Comment by 99Kies** [comment]
@NunoAlexandre I fixed the `TooExpensive` issue, This is because of my parameter Settings, my destweight setting is too large, and now back to `AssetIdConversionFailed`.

**Comment by NunoAlexandre** [comment]
@99Kies the links you have been posting here point to our own xcm config whereas you are using some other config. Do you have a link to your own repo?

**Comment by 99Kies** [comment]
> @NunoAlexandre I fixed the `TooExpensive` issue, This is because of my parameter Settings, my destweight setting is too large, and now back to `AssetIdConversionFailed`. ![image](https://user-images.githubusercontent.com/45918704/156392407-7c0571f7-9057-4f3d-b375-ece7260e3576.png)

But the previous error was in the sender, and now this error is in the target chain.

**Comment by NunoAlexandre** [comment]
@99Kies are you a contributor to the parachain B? I don't think this is right: https://github.com/DoraFactory/dorafactory-node/blob/add-orml-xtokens/runtime/src/lib.rs#L1031-L1032

Instead of `let ff: Vec<u8> = "FF".into();` try `let ff: Vec<u8> = CurrencyId::FF.encode();`.

If that doesn't work, I would set a `panic` or just a log printing the `l: MultiLocation` value to start by making sure that the location you are receiving is what you think it is. Then, make sure that you are matching on it correctly and thus converting it correctly to the internal `CurrencyId` variant.

**Comment by 99Kies** [comment]
@NunoAlexandre Yes, I am contributor on Parachain B. Thanks, I'll try your suggestion.
Do you mean to use `panic` to print, because I found that the code under runtime can't use `log::trace` or `log::info` to print.

**Comment by 99Kies** [comment]
@NunoAlexandre hi, I tried to modify it a few times, but it still failed, and the method of printing through the panic method is not very useful.
![image](https://user-images.githubusercontent.com/45918704/156427280-1bbdf282-b3f7-4736-8b03-6afceecd28b8.png)
```rust
impl Convert<MultiLocation, Option<CurrencyId>> for CurrencyIdConvert {
	fn convert(l: MultiLocation) -> Option<CurrencyId> {
        let ff: Vec<u8> = "FF".into();
        let dora: Vec<u8> = "DORA".into();
		if l == MultiLocation::parent() {
			return Some(CurrencyId::ROC);
		}

		match l {
			MultiLocation { parents, interior } if parents == 1 => match interior {
				X2(Parachain(1000), GeneralKey(k)) if k == ff => {
                    panic!("X2 FF =========================================");
                    Some(CurrencyId::FF)
                },
				X2(Parachain(2000), GeneralKey(k)) if k == dora => {
                    panic!("X2 DORA =========================================");
                    Some(CurrencyId::DORA)
                },
				_ => None,
			},
			MultiLocation { parents, interior } if parents == 0 => match interior {
				X1(GeneralKey(k)) if k == ff => {
                    panic!("X1 FF =========================================");
                    Some(CurrencyId::FF)
                },
				X1(GeneralKey(k)) if k == dora => {
                    panic!("X1 DORA =========================================");
                    Some(CurrencyId::DORA)
                },
				_ => None,
			},
			_ => None,
		}
	}
}
```
In addition, I wrote a separate code to verify the previous question.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/45918704/156427931-ac6a267f-e3d6-415f-a8d2-e0aef8877bf1.png">

**Comment by NunoAlexandre** [comment]
@99Kies 

> printing through the panic method is not very useful.

Can you expand on what you mean? Do you mean that the panic is never hit? If that's the case, that tells you that either your match is not handling what you expect to be handling or that that conversion is not being called.

My advise was to start by just placing a print or a panic (whatever works - if you see the print in the console that's better since it doesn't nuke your runtime) in the very first line of that conversion, to both make sure that it is being called and to make sure that the incoming `Multilocation` value is what you expect.

Regarding the `"FF.into()"" vs `CurrencyId::FF::encode()`, there you go :)

**Comment by 99Kies** [comment]
@NunoAlexandre But I can't print anything on runtime code.

**Comment by 99Kies** [comment]
i fixed it.

**Comment by 99Kies** [comment]
In fact, there is no problem with this configuration. It is my environment that has the problem. I will sort out an article in two days and put the link here then. Thanks for your help these days, especially for the tips related to printing logs under Runtime. I also found a way to print logs in runtime `use frame_support::runtime_print`.
Adding ORML requires attention to XcmConfig and asset transformation configuration. You can print out the asset conversion from `runtime_print` to help locate problems.
And pay attention to the `Barrier`, `Trader`, `AssetTransactor`, and `XcmSender` configuration items in `XcmConfig`.

@NunoAlexandre Thank you for keeping an eye on my problems and encouraging me.

**Comment by NunoAlexandre** [comment]
Glad you made it! Looking forward to that article. 👍

**Comment by 99Kies** [comment]
sorry I'm late, <https://learnblockchain.cn/article/3701>.
