### ISSUE TITLE
Pallet-pool: Tests for tranche.rs

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#678]
The new tranche.rs after the PR of #620 gets merged, contains no tests currently. 

Each method and the new functions should be unittested. 
Focus also on testing the reverse lib that we are using (needs to panic upon out-of-index).

**Comment by thea-leake** [comment]
Note about odd issue encountered:

With the `validate_next_tranche`->`Residual`->`Residual` => `false` change several other tests in the Pools pallet are failing with `"InvalidTrancheStructure"` on my end.

It looks like `validate_next_tranche` is sometimes getting `Residual`, `Residual`, when it should be getting `Residual`, `NonRedisual`.

Not sure if actual issue or just on my end at the moment.

Example:
in `pallets/pools/src/tests.rs:948` (execute_info_removed_after_epoch_execute):
```
		assert_ok!(Pools::create(
			pool_owner_origin.clone(),
			pool_owner.clone(),
			0,
			vec![
				TrancheInput {
					tranche_type: TrancheType::Residual,
					seniority: None,
					metadata: TrancheMetadata {
						token_name: BoundedVec::default(),
						token_symbol: BoundedVec::default(),
					}
				},
				TrancheInput {
					tranche_type: TrancheType::NonResidual {
						interest_rate_per_sec: senior_interest_rate,
						min_risk_buffer: Perquintill::from_percent(10),
					},
					seniority: None,
					metadata: TrancheMetadata {
						token_name: BoundedVec::default(),
						token_symbol: BoundedVec::default(),
					}
				},
			],
			CurrencyId::AUSD,
			10_000 * CURRENCY,
			None
		));
```
with the following added to valid_next_tranche
```
		let res = match (self, next) {
			(TrancheType::Residual, TrancheType::Residual) => "Res--Res::False",
			(TrancheType::Residual, TrancheType::NonResidual { .. }) => "Res--NonRes::True",
			(TrancheType::NonResidual { .. }, TrancheType::Residual) => "NonRes--Res::False",
			(TrancheType::NonResidual { .. }, TrancheType::NonResidual { .. }) => "RateComp",
		};
		println!("Comp result: {}", res);
```
we get a match on Res, Res:
```
---- tests::execute_info_removed_after_epoch_execute stdout ----
Comp result: Res--Res::False
thread 'tests::execute_info_removed_after_epoch_execute' panicked at 'Expected Ok(_). Got Err(
    Module(
        ModuleError {
            index: 4,
            error: [
                2,
                0,
                0,
                0,
            ],
            message: Some(
                "InvalidTrancheStructure",
            ),
        },
    ),
)', pallets/pools/src/tests.rs:948:9
```

**Comment by thea-leake** [comment]
Quick status update -- this has been put on pause for the last week or so for polkadot version upgrade work, will resume once that's been completed.

**Comment by thea-leake** [comment]
Picked up again, have been working Fri & today on getting tests working with current main etc.

**Comment by mustermeiszer** [comment]
Done in #1173
