### ISSUE TITLE
Fix pallet_restricted_tokens benchmarks

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#751]
With the recent changes to the `TracheId` type, the pallet_restricted_tokens` > `benchmarking` is failing to compile.

- [ ] Re-add `pallet_restricted_tokens` to the `development` and `altair` runtimes
- [ ] Fix compilation errors

**Comment by NunoAlexandre** [comment]
@mustermeiszer this is probably something you would smoke :)

**Comment by NunoAlexandre** [comment]
It can wait, for no we disabled it.

**Comment by mustermeiszer** [comment]
fixed compilation with #760.
