### ISSUE TITLE
discussion: Rethink integration-tests setup

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#774]
### Context

The new setup, introduced [here](https://github.com/centrifuge/centrifuge-chain/pull/739/), brought a structure that brings on a few assumptions:

1. Mutually exclusive runtimes - For all integration tests, only _one_ of our runtimes is to be used: either `altair` _or_ `centrifuge` _or_ `development`

2. All runtimes can be tested with interchangeably - The project should compile using any of the runtimes.

``` rust
/// Re-exports the correct runtimes that we run the integration tests with
/// This allows all other modules to use the import of `crate::chain::{...}`
/// in order to get the right stuff from the respective runtime.
mod chain {
	pub mod centrifuge {
		#[cfg(feature = "runtime-altair")]
		pub use altair::*;
		#[cfg(feature = "runtime-centrifuge")]
		pub use centrifuge::*;
		#[cfg(feature = "runtime-development")]
		pub use development::*;

		#[cfg(feature = "runtime-centrifuge")]
		pub mod centrifuge {
			pub use centrifuge_runtime::*;
			pub const PARA_ID: u32 = 2031;
		}

		#[cfg(feature = "runtime-altair")]
		pub mod altair {
			pub use altair_runtime::*;
			pub const PARA_ID: u32 = 2088;
		}

		#[cfg(feature = "runtime-development")]
		pub mod development {
			pub use development_runtime::*;
			pub const PARA_ID: u32 = 2000;
		}
	}

	pub mod relay {
		#[cfg(feature = "runtime-altair")]
		pub use kusama_runtime::*;
		#[cfg(feature = "runtime-centrifuge")]
		pub use polkadot_runtime::*;
		#[cfg(feature = "runtime-development")]
		pub use rococo_runtime::*;
	}
}
```

### Problems

I have been facing some problems with this new setup and the assumptions it forces upon:

1. In the future, we want the flexibility to tests cross-runtime XCM transfers. Assumption 1. above makes this impossible at the moment.

2. More important now, XCM tests are _NOT_ interchangeable - These tests require importing specific objects from a specific parachain and relaychain runtimes and they are meant to test a very specific runtime. For instance, `centrifuge-runtime` does NOT support XCM and thus any of the related imports, if compiled against the new `runtime-centrifuge` flag, will fail to resolve.

3. A minor issue, but the namespace `crate::chain::centrifuge` is confusing as it reads as if it's referring to the `centrifuge` runtime when in fact it's just an alias for whichever of the three runtimes has been enabled via the `--features` option.

### Possible solutions

1. Feature-flag specific tests

Since different test may have different natures and levels of flexibility, we can feature flag their imports. That would mean that instead of having:

``` rust
mod pools;
mod xcm;
```

We would have:

``` rust
#[cfg(any(
	feature = "runtime-centrifuge",
	feature = "runtime-development",
))]
mod pools;

// We are only in e2e test XCM on Altair
#[cfg(feature = "runtime-altair")]
mod xcm;
```

**Pros/Cons**

* ➕ This fixes assumption and problem number 2 by only allowing the interchangeable nature of the setup in tests where that it possible.
* ➖ Does not fix assumption and problem number 1
* ➖ We would need to make run we run the integration tests with all feature flags to ensure that all integration tests are covered

2. Drop the feature flags and the `chain` mod all together

Integration tests are meant to ensure, as far as it is possible, that a specific component will work in production.
Therefore, I am of the opinion that such tests should be specific regarding the component they are covering.

For example, the `pools` tests are critical to be valid on the `centrifuge` runtime, as being valid on the `development` runtime does not give us any certainty. But as of now, unless specified otherwise, those tests run against the `development` runtime instead. Perhaps this is fine for now if the pools is not yet mature in `centrifuge` - I am hoping to just show case the stance.

**Pros/Cons**

* ➖ Longer build times since all runtimes will be compiled 
    `altair`, `centrifuge`, `development` for the parachains and `rococo`, `kusama`, `polkadot` for the relay - This problem will be reduced if we stop e2e testing against the `development` runtime as suggested above.

* ➕ Fixes all the assumptions and the problems described above

### Conclusion

Currently, the current setup is quite an _entanglement_ for the XCM tests since they **need** to be specific about both the parachain and relaychain runtimes it needs to run in.

I prefer the suggestion 2. as it's the simplest and fixes all the issues described. Since we don't need to package the `integration-tests`, total size is irrelevant and build times are incremental so I wouldn't over-consider the build times point. Shall we in the future face a scenario where we actually need to feature-flag some parts, then we can re-introduce (some of) the runtime feature flags.

**Comment by NunoAlexandre** [comment]
@mustermeiszer @branan @offerijns keen on having your thoughts on this 🙌

**Comment by mustermeiszer** [comment]
I think the fact that we want to test pools against altair and centrifuge would duplicate a lot of code, if we want to run it without the `chain` generalization. 

I would prefer feature-guards. So that we test pools for centrifuge and altair and generalize the "chain" import mechanism there. And xcm can have its own feature-guard.

**Comment by NunoAlexandre** [comment]
> I think the fact that we want to test pools against altair and centrifuge would duplicate a lot of code, if we want to run it without the `chain` generalization.
> 
> I would prefer feature-guards. So that we test pools for centrifuge and altair and generalize the "chain" import mechanism there. And xcm can have its own feature-guard.
> 
> So option 1. and still get rid of the generalized import in the `chains` mod.

Fair enough, yeah!

We can indeed keep the abstraction for tests where we want to test the same logic against different runtimes while still allow for the other runtimes to be available for other runtimes that are needed for other tests. I will follow this up this week hopefully.

**Comment by NunoAlexandre** [comment]
Done in #779
