### ISSUE TITLE
Additional RPC Methods Discussion

### ISSUE THREAD

**Issue by onnovisser** [centrifuge/centrifuge-chain#797]
Issue for discussing additional runtime RPC Methods.

## Method Ideas
* `calculateCollect` -> Shows the amount a user receives upon calling collect (Are we passing the `n_epochs` parameter here or simply go to latest?)
* `pools_poolAdmin` -> Retrieves all admin accounts for a given pool (one for each admin role of a pool, `MemberlistAdmin`, etc.)
- tranche investors also

**Comment by onnovisser** [comment]
To start the discussion, a piece of data that's currently quite awkward to request is the permissions for a single pool, because they can only be retrieved by account. If I want to get all the admins for a pool or all investors, I first have to get all the storage keys for all the permissions and, filter them by pool id, before then requesting the data.

**Comment by mustermeiszer** [comment]
cc: @offerijns @branan

**Comment by mustermeiszer** [comment]
* should we add qerying roles  for all `PoolRole`s? (i.e. `MemberListAdmin`, etc.)
 * What about also querying investors?

**Comment by onnovisser** [comment]
The UI needs to show both all investors and all admins for a pool. So having both would be ideal.
Wouldn't matter if it's in 1 rpc call or 2, so whatever is easiest.

**Comment by onnovisser** [comment]
Also Jeroen suggested exposing the `calculate_collect` function as an rpc method

**Comment by mustermeiszer** [comment]
Closing. Will open an epic for this.
