### ISSUE TITLE
Update pool permissions

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#799]
## Roles
On pool creation, the admin should receive the `PoolAdmin` and `PermissionAdmin` roles.

`PoolAdmin`
- Update metadata
- Update tranche structure
- Update parameters (min epoch time, ...)

`PermissionAdmin`
- Manage roles for this pool

`MemberlistAdmin`
- Manage tranche investors

`LiquidityAdmin`
- Manage max reserve

`Borrower`
- Create loans
- Borrow, repay, close loans

`PricingAdmin`
- Price new loans

`LoanAdmin`
- Price ongoing loans
- Admin write-off loans
- Add write off groups

#### Simple pool > One issuer is also the AO and prices it's own assets
Issuer Multisig: `PoolAdmin`, `PermissionAdmin`, `LoanAdmin`
Issuer separate accounts: `LiquidityAdmin`, `MemberlistAdmin`, `Borrower`, `PricingAdmin`

#### Simple pool > One issuer is also the AO, third party pricing
Issuer Multisig: `PoolAdmin`, `PermissionAdmin`, `LoanAdmin`
Issuer separate accounts: `LiquidityAdmin`, `MemberlistAdmin`, `Borrower`
Underwriter, Servicer: `PricingAdmin`, `LoanAdmin`

#### Pool with trustee involved, and multiple asset originators
Issuer Multisig: `PoolAdmin`
Issuer separate accounts: `LiquidityAdmin`, `MemberlistAdmin`
Trustee: `PermissionAdmin`, `PricingAdmin`, `LoanAdmin`
Asset originators: `Borrower`

**Comment by offerijns** [comment]
Partially. `RiskAdmin` was renamed to `LoanAdmin`. We haven't created the new `PermissionAdmin` role yet, but I think we need to discuss if/how we actually want to do this.

**Comment by mustermeiszer** [comment]
@offerijns What would be the things the permission admin could actually do?

**Comment by offerijns** [comment]
Let's close this. The idea was to separate permission management (adding/removing other admins basically) from the rest of the PoolAdmin roles. But we've discarded this as it unnecessarily complicates the permissions.
