### ISSUE TITLE
feature: Introduce orml `asset_registry`

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#825]
## What it is

The orml [`asset_registry`[(https://github.com/open-web3-stack/open-runtime-module-library/tree/master/asset-registry) pallet, inspired in Acala's custom pallet with the same name, has beeb made general-purpose and released under the `orml` library.

This pallet allows for asset registration at run-time, without the need to hardcode new token variants into the runtime code and a follow up runtime upgrade. Instead, it allows us to configure it so that, through democracy, new assets can be registered and thus supported in our runtime(s).

### Api

The pallet offers two extrinsics:

1. `register_asset`

``` rust
pub fn register_asset(
	origin: OriginFor<T>,
	metadata: AssetMetadata<T::Balance, T::CustomMetadata>,
	asset_id: Option<T::AssetId>,
)
```

2. `update_asset`

``` rust
pub fn update_asset(
	origin: OriginFor<T>,
	asset_id: T::AssetId,
	decimals: Option<u32>,
	name: Option<Vec<u8>>,
	symbol: Option<Vec<u8>>,
	existential_deposit: Option<T::Balance>,
	location: Option<Option<VersionedMultiLocation>>,
	additional: Option<T::CustomMetadata>,
)
```

where

``` rust
pub struct AssetMetadata<Balance, CustomMetadata: Parameter + Member + TypeInfo> {
	pub decimals: u32,
	pub name: Vec<u8>,
	pub symbol: Vec<u8>,
	pub existential_deposit: Balance,
	pub location: Option<VersionedMultiLocation>,
	pub additional: CustomMetadata,
}
```

In other words, the pallet expects a pre-defined set of asset properties to be provided which are common amongst all assets, and in addition provides a field to store additional custom metadata fields.

## What it is _not_

The `asset_registry` is _not_ an implementation of the `frame_support::traits::fungibles`, like `orml_tokens` is. I.e, this pallet does not concern itself with `Inspect`ing nor `Transfer`ing assets of different currencies.

Instead, it _only_ serves as a registry of asset metadata. Other pallets, such as `orml_tokens` can - and in our case will - be responsible for the bookkeeping of these assets.

## Why

Now that have landed our first XCM integration with Acala and have learned throughly how to setup XCM to add support for new tokens, we also observed that for each new token we may wish to make XCM-transferrable, a new runtime upgrade would be required.

#### No runtime-upgrade required

Now that the `asset_registry` has been made general-purpose by and for the community, we can take advantage of its features and leverage our XCM setup so that new tokens can be made seamlessly XCM-transferrable by simply registering them in this `asset_registry`, without the need for a runtime upgrade.

#### Standard token metadata api

Currently, we do not expose a general api for querying an asset's metadata. All of this data is [currently hardcoded](https://github.com/centrifuge/centrifuge-chain/blob/3bf284368d09cc05fa98947a723fef7a5c9b1c78/libs/common-types/src/tokens.rs#L22-L81).

We are currently thinking about how we could standardize querying asset metadata not only for new assets we will register in `asset_registry`, but also for the currently supported tokens (`Native` (i.e, `AIR`/`CFG`), `KSM`, `KUSD`/`AUSD`). The `asset_registry` would very well make this possible.

---

### 1. Plug `asset-registry` into our runtime(s)

[`general`]
- [x] Refactor our `enum CurrencyId` to be used as the `AssetId` type param of this pallet https://github.com/centrifuge/centrifuge-chain/issues/826

[`development-runtime` + `altair_runtime`]
- [x] Add the `asset-registry` pallet to the runtime

### 2. Refactor and leverage our XCM config to make use of `asset-registry`

We should then address this second part separately.

[`development-runtime` + `altair_runtime`]
- [x] Refactor the XCM configuration to lookup assets in `asset-registry` for outgoing transfers and reverse-lookup by location for incoming transfers
- [x] (If possible) Include the `asset-registry`/`benchmarks`

[`integration-tests`]
- [x] Extend the XCM tests to cover assets registered in the asset-registry

**Comment by mustermeiszer** [comment]
Closed right @NunoAlexandre ?
