### ISSUE TITLE
refactor: `CurrencyId`

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#826]
## What

Our current `CurrencyId` type is defined as follows:

``` rust
pub enum CurrencyId {
	// The Native token, representing AIR in Altair and CFG in Centrifuge.
	Native,

	// A Tranche token
	Tranche(u64, [u8; 16]),

	/// Kusama KSM
	KSM,

	/// Karura Dollar
	KUSD,

	/// Acala Dollar
	/// Note: KUSD and AUSD will be merged into a single token, AUSD.
	AUSD,

	Permissioned(PermissionedCurrency),
}
```

This type is then used as the currency id type for other pallets, namely `restricted_tokens`, `orml_tokens`, and `xTokens`. I.e, each variant is encoded and used as a key identifying an asset on those pallets. With the exception of `xTokens`, that encoded key is stored on chain, for example when storing the balance of an account for a specific asset.

## Requirements

1. Allow for identifying assets stored in `asset-registry` (see #825)
2. Allow for specifying or categorise assets based on some properties
   - Whether a token is _permissioned_, such as the `Tranche` token
   - Whether a token should be `Mintable` - an upcoming use case
3. Support for specific native currencies for the different runtimes, i.e, `AIR`, `CFG`, `DEVEL`, instead of just a single `Native`
    - This will become specifically important when cross-network XCM transfers become possible
    - Note: this would require a migration

Requirement 1. is mandatory and urgent; 
Requirement 2. is an important one but not yet urgent;
Requirement 3. is a nice to have but can wait.

## Proposal

To prevent us to dive into a gigantic PR, I propose that we break this in phases and focus on deliverables for the timelines we aim to respect.

### Phase 1

In phase 1, we focus on delivering on Requirement 1 and lay the foundation for Requirement 2.

**Steps**

- Add a `ForeignAsset` variant to `CurrencyId`
- Define a `CustomMetadata` type used in `asset-registry` that could capture whether a token is:
  - Permissioned
  - Mintable
  - Optional XCM-useful fields (for instance, `fee_per_second`)

This allows us to:

- Register and thus support new tokens to be XCM-transferrable, namely USDC
- Register other tokens for testing purposes with the Permissioned & Mintable trait flags allowed

### Phase 2

- Drop the `CurrencyId::Permissioned` variant and register those tokens in `asset-registry` with the correct `Permissioned` & `Mintable` flags instead
- Possibly extend the `CustomMetdata` type with more useful flags to categorise tokens more gradually

### Phase 3

- Deprecate the `CurrencyId::Native` variant and introduce at least `Currency::AIR` and `Currency::CFG`
   - Make `CurrencyId::AIR` the native token in `Altair` and `CurrencyId::CFG` the native token in `Centrifuge`
   - Write migration code to migrate all data associated with `Native` to be associated to `AIR` and `CFG` in `Altair` and `Centrifuge`, respectively 

Additionally, we can also care to:
 - Drop the harcoded variants we have for `KSM, `KUSD`, and `AUSD` to have them as registered assets in the `asset-registry` and merge `KUSD` as `AUSD`
       - Write migration code to migrate all data associated with said variants to be associated with the respective `CurrencyId::RegisteredToken(<id>)` variant.

**Comment by NunoAlexandre** [comment]
### Next steps

- Drop `CurrencyId::AUSD` and `CurrencyId::KSM`
  1. Register those currencies in the Asset Registry
  2. Migrate all balances from each respectively to their new registered `CurrencyId::ForeignAsset` variant
  3. Drop the deprecated variants

**Comment by NunoAlexandre** [comment]
_For the record_

Pre-image registering `CurrencyId::Native` and `DOT` on `Centrifuge`: `0x6de31686f6a4fbf1584f91e45961862f44e5a692b23a122bc29e26c5e2275d60`

We don't actually _need_ to register `DOT` for this migration / refactor but it's surely doesn't hurt to have it register already.

**Comment by mustermeiszer** [comment]
How would the currenyId enum then look like? And what kind of metadata do we have on the registry?

**Comment by NunoAlexandre** [comment]
> How would the currenyId enum then look like? And what kind of metadata do we have on the registry?

In the end, we would have it as:

``` rust=
pub enum CurrencyId {
  Native,
  Tranche(_, _),
  ForeignAsset(_),
}
```

**Comment by mustermeiszer** [comment]
Just wanted to see it here and discuss if it is sufficient. Like the metadata in the `orml-registry`

**Comment by NunoAlexandre** [comment]
> Just wanted to see it here

Makes sense!

> Like the metadata in the `orml-registry`

The changes that this issue is concerned with don't have any impact on the metadata properties so I don't know that it's useful to add that in here? Do you have something specific in mind?

**Comment by NunoAlexandre** [comment]
For the record, I have tested that we can use `#[repr(u8)]`, which is stable since `1.67.0-nightly`, and therefore keep all the currency variants we want to keep all with the same index and therefore not mess up their encoding/decoding, which would impact all balances entries for `ForeignAsset`s.

```
#[test]
pub fn test_currency_id_refactor() {
	use codec::{Encode, Decode};

	#[derive(Encode, Decode, Clone, PartialEq, Eq)]
	#[repr(u8)]
	pub enum CurrencyIdBefore {
		// 0
		Native = 0,
		// 1 + value
		Tranche(u64) = 1,
		// 2
		AUSD = 2,
		// 3
		KSM = 3,
		// 4 + value
		ForeignAsset(u128) = 4,
	};

	#[derive(Encode, Decode, Clone, PartialEq, Eq)]
	#[repr(u8)]
	pub enum CurrencyIdAfter {
		// 0
		Native = 0,
		// 1 + value
		Tranche(u64) = 1,
		// 4 + value
		ForeignAsset(u128) = 4,
	};

	assert_eq!(CurrencyIdBefore::Native.encode(), CurrencyIdAfter::Native.encode());
	assert_eq!(CurrencyIdBefore::Tranche(123).encode(), CurrencyIdAfter::Tranche(123).encode());

	// ensure it doesn't encode just to the repr u8 value
	assert_eq!(hex::encode(CurrencyIdBefore::ForeignAsset(91).encode()), "045b000000000000000000000000000000");
	assert_eq!(CurrencyIdBefore::ForeignAsset(91).encode(), CurrencyIdAfter::ForeignAsset(91).encode());
}
```

This means that we only need to migrate AUSD and KSM balances to their new corresponding `ForeignAsset` entry and leave all the existing `ForeignAsset` entries as they are. Or we can also opt just to migrate everything and not have to use the `#[repr(u8)]` approach; the advantage of the latter is that it makes it very much future proof shall we need to add or move move variants around.
