### ISSUE TITLE
permissions: Add `MintableCurrencyIssuer` role

### ISSUE THREAD

**Issue by NunoAlexandre** [centrifuge/centrifuge-chain#831]
On implementing mintable permissions, we likely should add a `MintableCurrencyIssuer` role to the permissions pallet, instead of the current `PermissionedCurrencyIssuer`, as this can be used for both. The `mintable: bool` makes a lot of sense then.

_Originally posted by @offerijns in https://github.com/centrifuge/centrifuge-chain/pull/829#discussion_r896903701_

**Comment by mustermeiszer** [comment]
@NunoAlexandre do we still need this?

**Comment by NunoAlexandre** [comment]
@mustermeiszer thanks for the ping 👍 

This was in the context of an integration we had on the table a couple of months back that we don't have to respond to now. The design idea behind this is still valid tho.

Leaving it to @offerijns
