### ISSUE TITLE
Register tranche token in asset-registry

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#842]
- [x] Add `create_asset_metadata(pool_currency, token_name, token_symbol): AssetMetadata` method to `tranche.rs`

Add `AssetRegistry.Inspect` trait to `pools` runtime parameters. Call `Inspect.metadata(pool.currency)` to retrieve the pool currency decimals.

Add `ParachainId`constant to `pools` runtime parameters.

This will accept pool currency, token name and token symbol as arguments and return the following:

```rust
asset_metadata = {
  decimals: pool_currency.decimals,
  name: token_name,
  symbol: token_symbol,
  existential_deposit: Zero::zero(),
  location: Some(MultiLocation::new(
    1,
      X2(
        Parachain(parachain_id),
        GeneralKey(tranche_id.to_vec()),
      ),
    );
  ),
  additional: {
    mintable: false,
    permissioned: false,
    pool_currency: false,
    xcm: {
      fee_per_second: None,
    }
  },
}
```

- [x] Register tranche tokens on pool creation

Add `MaxTokenNameLength` and `MaxTokenSymbolLength` runtime parameters to the `pools` pallet.

Adapt https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/pools/src/tranche.rs#L58 to
```rust
pub struct TrancheMetadata<MaxTokenNameLength, MaxTokenSymbolLength> {
	pub token_name: BoundedVec<u8, MaxTokenNameLength>,
	pub token_symbol: BoundedVec<u8, MaxTokenSymbolLength>,
}

pub struct TrancheInput<Rate, MaxTokenNameLength, MaxTokenSymbolLength> {
	pub tranche_type: TrancheType<Rage>,
	pub seniority: Option<Seniority>,
	pub metadata: TrancheMetadata<MaxTokenNameLength, MaxTokenSymbolLength>,
}
```

Add `AssetRegistry.Mutate` trait to `pools` runtime parameters.

Call [`register_asset ` ](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/asset-registry/src/impls.rs#L199) for each tranche.

- [x] Update token metadata on `pools.update`

Adapt https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/pools/src/lib.rs#L115 to:
```rust
pub struct PoolChanges<Rate, MaxTokenNameLength, MaxTokenSymbolLength> {
	pub tranches: Change<Vec<TrancheUpdate<Rate>>>,
	pub tranche_metadata: Change<Vec<TrancheMetadata<MaxTokenNameLength, MaxTokenSymbolLength>>>,
	pub min_epoch_time: Change<Moment>,
	pub max_nav_age: Change<Moment>,
}
```

In `update`, validate that `tranche_metadata` length is equal to `tranches.new_value` or to the existing tranches.

In `do_update_pool`, if `changes.tranche_metadata` contains new metadata for existing tranches, call [`update_asset ` ](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/asset-registry/src/impls.rs#L206) for each tranche. If `changes.tranches` contains new tranches that are being added, call [`register_asset ` ](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/asset-registry/src/impls.rs#L199) for each of these.

### Dependencies

Blocked by https://github.com/centrifuge/centrifuge-chain/issues/878

**Comment by NunoAlexandre** [comment]
> * Should we adapt `pools.set_metadata`, `pools.create`/`pools.update`, or add a new method `pools.set_tranche_metadata`?

Out of curiosity, which advantage do you see for the latter option? Asking since at first sight it makes sense to me to ensure that the metadata when either of the 3 extrinsics - that can alter metadata - are executed.

**Comment by branan** [comment]
I think the symbol info should come along any time we create or modify tranches, so as part of the `create` and `update` calls sounds right to me.

The `update` logic will of course need to _modify_ the token metadata in the registry, not create a new token

**Comment by branan** [comment]
I'd propose a slightly different set of struct changes here:

```rust
pub struct TrancheMetadata<MaxTokenNameLength, MaxTokenSymbolLength> {
	pub token_name: BoundedVec<u8, MaxTokenNameLength>,
	pub token_symbol: BoundedVec<u8, MaxTokenSymbolLength>,
}

pub struct TrancheInput<Rate, MaxTokenNameLength, MaxTokenSymbolLength> {
	pub tranche_type: TrancheType<Rage>,
	pub seniority: Option<Seniority>,
	pub metadata: TrancheMetadata<MaxTokenNameLength, MaxTokenSymbolLength>,
}

pub struct TrancheUpdate<Rate, MaxTokenNameLength, MaxTokenSymbolLength> {
	pub tranche_type: TrancheType<Rage>,
	pub seniority: Option<Seniority>,
}

pub struct PoolChanges<Rate, MaxTokenNameLength, MaxTokenSymbolLength> {
	pub tranches: Change<Vec<TrancheUpdate<Rate>>>,
	pub tranche_metadata: Change<Vec<TrancheMetadta<MaxTokenNameLength, MaxTokenSymbolLength>>>,
	pub min_epoch_time: Change<Moment>,
	pub max_nav_age: Change<Moment>,
}
```

On creation, we require metadata input for tranches. On update, metadata is optional (though the logic will eventually require it to be passed along if tranches are added or removed). We could also special-case `update` for where only the metadata changes to not require a minimum update period in this case.

**Comment by gruberb** [comment]
@branan @offerijns Regarding `token_name` and `token_symbol`: Are we creating a generic one for each tranche, or does the UI have to submit a name and symbol? Asking if I have to adjust the signature of the `create` and `update` functions, and if not, was there a prior discussion which generic names we want to use?

**Comment by offerijns** [comment]
@gruberb It should be passed by the UI. `create` accepts `tranches: Vec<TrancheInput>` and `TrancheInput` should contain the name and symbol. `update` accepts `changes: PoolChanges` and `PoolChanges` should contain `tranches_metadata` with the name/symbols.

**Comment by gruberb** [comment]
I believe we have to update `AssetMetadata` in the open-runtime-module-library to support `BoundedVec` 
https://github.com/open-web3-stack/open-runtime-module-library/blob/master/traits/src/asset_registry.rs#L24 since we are using it through `AssetRegistry::register_asset` .

**Comment by gruberb** [comment]
Closed with https://github.com/centrifuge/centrifuge-chain/pull/947
