### ISSUE TITLE
chainbridge-ui incorrect/missed information

### ISSUE THREAD

**Issue by ImdioR** [centrifuge/centrifuge-chain#859]
**Good day Centrifuge Team**
I was not able to open a ticket in  chainbridge-ui section, so I opened it here. 
I would like to report feedback about the bridge working and how could be improved.
A few users reported incorrect working of the bridge:
1.  ![image](https://user-images.githubusercontent.com/90972248/178142208-3fa9aa19-6b9b-4db2-a13a-9b9214143a19.png)
and add this screenshot in the report.
In my opinion, the actual information displayed is not correct or not sufficient to understand the error for the end-user. And could let end-user think that bridge is not working now.

2. Same error with Console mode:
![image](https://user-images.githubusercontent.com/90972248/178142192-e86e7bff-3a11-4ed8-b58d-40e514ba3110.png)

Metamask - RPC Error: Gas required exceeds Allowance  - or in simple words ETH balance not sufficient to run the bridge and cover the transaction fee.

Will be cool if the end-users could see the exact description of the error - ETH balance not sufficient, CFG balance is not enough to cover the transaction fee and etc..
Thank you in advance.
Best regards.

**Comment by mustermeiszer** [comment]
@ImdioR is this still the case?

CC: @mikiquantum

**Comment by ImdioR** [comment]
Hi, i guess not yet anymore.
Thank you anyway. I`m closing it.
