### ISSUE TITLE
Add field names to pallet `Event` variants

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#871]
Per https://github.com/paritytech/substrate/issues/9903

- [x] pools pallet
- [x] loans pallet (https://github.com/centrifuge/centrifuge-chain/pull/863)
- [x] claims pallet (https://github.com/centrifuge/centrifuge-chain/pull/875)
- [x] collator-allowlist pallet (https://github.com/centrifuge/centrifuge-chain/pull/874)
- [x] keystore pallet (https://github.com/centrifuge/centrifuge-chain/pull/873)
- [x] permissions pallet (https://github.com/centrifuge/centrifuge-chain/pull/872)

**Comment by mustermeiszer** [comment]
This is done.

**Comment by mustermeiszer** [comment]
> I have added a PR per pallet because I thought it would imply more changes. Maybe only one PR would have been easier to review, sorry!

I actually like that. I should do smaller PRs more often.
