### ISSUE TITLE
Replace all `Vec`s with `BoundedVec`s

### ISSUE THREAD

**Issue by offerijns** [centrifuge/centrifuge-chain#897]
For [Weights V2](https://github.com/paritytech/substrate/pull/10918), we will (eventually) need to add `MaxEncodedLen` to all storage values. This means replacing all `Vec`s in storage with `BoundedVec`s and adding runtime parameters (or hardcoded consts when it makes more sense) for these bounds.

On first review, it looks like there's currently unbounded `Vec`s in these pallets:
- [x] anchors pallet: https://github.com/centrifuge/centrifuge-chain/pull/980
- [x] ~~bridge pallet~~
- [x] loans pallet: https://github.com/centrifuge/centrifuge-chain/pull/990
- [x] pools pallet: https://github.com/centrifuge/centrifuge-chain/pull/979

**Comment by lemunozm** [comment]
`pallet-bridge` seems to not use any Vec in its storage, only in the `GenesisConfig`, but I think this is not related to WeightsV2.

**Comment by lemunozm** [comment]
`pallet-loans` has a `Vec` in its storage, inside of the `WriteOffGroup` type. Seems like it's conceptually something unlimited. Anybody could add any number of write-offs using `add_write_off_group()`. 

@branan @mustermeiszer @gruberb Any recommendation to tackle this? We also need to give some kind of error in `add_write_off_group()` if we reach the new bound.

**Comment by mustermeiszer** [comment]
@lemunozm we have not yet fully speced the changes to write-off groups. I think to unblock you here, the simplest would be to add a bounding associated type and simply error out with `TooManyWriteOfGroups`. We currently do not allow to remove them, so they would be stuck in this case, but we will refactor this code anyways heavily, so no need to spend much time on this now.

**Comment by offerijns** [comment]
@lemunozm This limit already is implemented: https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/loans/src/functions.rs#L637 The `BoundedVec` should just be bounded by `T:: MaxWriteOffGroups`.

**Comment by lemunozm** [comment]
I must be blind, you're right. Thanks @offerijns!
