### ISSUE TITLE
Custom Rounding for `Rate`

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#931]
Implement a few methods for our custom `FixedPointNumber` type `Rate` in `runtime_common`, that allow us to choose a rounding preference from time to time. One important aspect here is, that we use `Rate` always behind a trait bound. Meaning we can not use non-trait methods. Hence, we must define a trait for this.

### Implementation Draft
```rust
// Not sure if we actually need FixedPointOperand as a super trait
pub trait FixedPointOperandExtension: FixedPointOperand {
       fn checked_mul_floor(&self, int: &Self::Inner) -> Option<Self::Inner>;

       fn checked_mul_ceil(&self, int: &Self::Inner) -> Option<Self::Inner>;

       fn saturating_mul_floor(&self, int: &Self::Inner) -> Self::Inner;

       fn saturating_mul_ceil(&self, int: &Self::Inner) -> Self::Inner;
}
```

**Comment by thea-leake** [comment]
PR for issue now in review: https://github.com/centrifuge/centrifuge-chain/pull/1006
