### ISSUE TITLE
Write-off Group Changes

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#939]
Short describtion of the logic that write-offs should follow:
* 100% write-off of a loan means it DOES NOT accrue value anymore
   * BUT it can NOT be closes -> Repayment is always possible
* Write-off policies
    * on a PER POOL basis
    * CAN be adjusted
    * changes MUST go through an `UpdateGuard` -> loan says I want to update my write-off policies to pallet-pools. Pallet-pools checks if all restrictions for this are given, of not loans must store update and come back at a later point
* Write-off policies
    * Admins can ONLY make write-offs MORE SEVERE, NOT LESS
    * Removal of write-offs CAN ONLY be made by the system automatically upon repayments
    * Policy write-offs, i.e. the system automatically can always write-off less OR more severe
    * `penalty_rate + interest_rate >= 1` at all times

### Implementation 
**From:**
```rust
WriteOffGroups = Vec<WriteOffGroup>

loan.status = WriteOffStatus {
    None,
    WrittenOff { group_id } ,
    WrittenOffByAdmin { perc, penalty },
}

add_write_off_group(..)
archive_write_off_group(..)
```
**To =>**

```rust
WriteOffPolicy = Vec<WriteOffState>

loan.status = WriteOffStatus {
    None,
    WrittenDownByPolicy { perc, penalty },
    WrittenDownByAdmin { perc, penalty },
    WrittenOff, // once in this state, there's no more interest charged (TODO), perc = 100%, penalty = 0% by default
}

update_write_off_policy(policy: Vec<WriteOffState>)
```

**Comment by lemunozm** [comment]
@mustermeiszer in the `from` section of the issue, there is an `archive_write_off_group` method. I can not find this in the repo. Is it something removed or never added?

**Comment by mustermeiszer** [comment]
@lemunozm will take a look tomorrow. Is this fine, or are you blocked by this?

**Comment by offerijns** [comment]
It doesn't exist, this is what we would have had to add with the current append-only write off group model in order to remove write-off groups. So the proposal is basically, rather than having an append-only vec with the ability to archive write-off groups by toggling an `archived` boolean on separate groups, we instead update the entire vec on any write-off policy change.

**Comment by lemunozm** [comment]
> Admins can ONLY make write-offs MORE SEVERE, NOT LESS

I understand that this can no longer be true if we want that the admins write off back to 0% in some cases, right?

**Comment by offerijns** [comment]
@lemunozm the goal here is that the write-off policy is the enforced minimum. So if a loan is overdue by 30 days and the write-off policy states that this loan should be written down at least 10%, then an admin can't reverse this.

But if you have a scenario where the write-off policy does not apply yet,  e.g. a loan is not overdue yet but it was written down by an admin in expectation of a loan not being fully repaid, but this expectation changes, then the admin should be able to "un write it off" back to 0%.

**Comment by lemunozm** [comment]
Not clear to me what `WriteOffState` is in the example above. Does it have the same attributes as `WrittenOffGroup`, or it contains different data?

**Comment by lemunozm** [comment]
A minor question here: The user who calls `update_write_off_policy(policy: Vec<WriteOffState>)` is expected to use the interest per rate per sec or per year?

**Comment by mustermeiszer** [comment]
cc @branan

**Comment by branan** [comment]
In order to prevent too much storage bloat (and to protect our users against mistakes), we restrict rates to those that are financially useful (not too many decimals and within a reasonable range for an interest rate). This means any rates that come from users need to be yearly, so we can verify they meet those properties easily.

For write-off groups (whose rate is used to modify the base rate of the loan), the current logic is at https://github.com/centrifuge/centrifuge-chain/blob/main/pallets/interest-accrual/src/lib.rs#L469-L477

**Comment by mustermeiszer** [comment]
@branan WDYT about changing the interface as the resulting `interestrate_per_sec = old_interest_rate_per_sec + InterestAccrual::convert_additive_rate_to_per_sec(additive_interest_rate_per_year)` could be an invalid interest rate. 

&rarr; This could lead to still bloating the `on_initialize` as possibly more interest rates per second are the result. 

I am not really sure what a good change would be. The easiest would be if we would still store the `interest_rate_per_year` in the `LoanInfo`. cc: @lemunozm 

Then we could do 

```rust
fn reference_additive_rate(
                 first_interest_rate_per_year: T::InterestRate,
		second_interest_rate_per_year: T::InterestRate,
	) -> Result<T::InterestRate, DispatchError> {
                let interest_rate_per_year =  Self::reference_yearly_interest_rate(
                        first_interst_rate_per_year.ensure_add(second_interest_rate_per_year)?
                 )?;
		Ok(interest_rate_per_sec)
	}
```

**Comment by lemunozm** [comment]
I like that approach. If I understand it well, in this way, the input extrinsic parameters and storage will use `per_year`, and when we need to use them for computation we just convert them to the `per_sec`, right?

**Comment by lemunozm** [comment]
Another question, if the percentage goes from 0% to 100%, could fit better a `Percent` (or similar) instead of `Rate`? Using `Rate`, someone could add values as 300%, I think

**Comment by lemunozm** [comment]
@mustermeiszer in the issue discription you say:
```rust
WrittenOff, // once in this state, there's no more interest charged (TODO), perc = 100%, penalty = 0% by default
```
Why is the penalty 0%? Is it because once it is written down with the percentage of 100%, it doesn't matter if the penalty is 0% or 100%?

**Comment by mustermeiszer** [comment]
The wording is bad.

- write off 100% means no more interest accruing. No normal one, no penalty one.

If the penalty must be zero for that, I don't know. Depends on how we build it. 

In theory the PV calculation can be non zero, but I guess we want it to be zero for now. Meaning the valuation method must know the write off state.
