### ISSUE TITLE
RtAPI - PV of a Loan

### ISSUE THREAD

**Issue by mustermeiszer** [centrifuge/centrifuge-chain#942]
Allow to retrieve the PV of a loan. 
It is important that the `now` defining the value is optionally providable, to get a glimbs into the future. Past should be forbidden, as this is messy.

**Comment by lemunozm** [comment]
It's already done here: https://github.com/centrifuge/centrifuge-chain/blob/main/pallets/loans/src/entities/loans.rs#L529

**Comment by mustermeiszer** [comment]
@lemunozm but this is the lastly computed value, we would want the latest value available, or is the loans logic updating all loans when constructing the portfolio?

**Comment by lemunozm** [comment]
Yes, the current line above returns the present value computed just at the moment when it's retrieved. If you want the present value at the moment when the portfolio was updated, you can fetch then the `PortfolioValuation` type from the storage, which holds the values for all loans: https://github.com/centrifuge/centrifuge-chain/blob/main/pallets/loans/src/lib.rs#L1020

**Comment by lemunozm** [comment]
Then, it's done in the first shared line, where the present value is computed with `now()`
