### ISSUE TITLE
Create `pools-registry` pallet

### ISSUE THREAD

**Issue by gruberb** [centrifuge/centrifuge-chain#956]
We want to move `Metadata` related code out of the `pools-pallet` into its own pallet. 

- [x] Move https://github.com/centrifuge/centrifuge-chain/issues/842 into `pools-registry`
- [x] Moving `metadata` out of the `Pool` struct and create a new Storage item within `pools-registry` with `PoolsMetadata<PoolId, Metadata>`
- [x] Move `set_metadata` (https://github.com/centrifuge/centrifuge-chain/blob/parachain/pallets/pools/src/lib.rs#L796-L830) into `pools-registry`

@mustermeiszer and @offerijns  had some more suggestions what `pools-registry` should do.

**Comment by offerijns** [comment]
One method we could add to `pools-registry` is `set_pool_name`, for https://github.com/centrifuge/centrifuge-chain/issues/701

**Comment by mustermeiszer** [comment]
Not sure if we need this already in this version. But we should have a `UpdateGuard` at some point in the near future.

**Comment by gruberb** [comment]
Going through the changes, I collected some "major" API changes:

- When we `create` a `Pool`, we send metadata. If we want to move all `metadata` related functionality into `pools-registry`, we have to always have two calls from now on and adjust the `create` paramaters.
- Same goes for `update` `Pool` (which has `TrancheMetadata` included in the `update` call)

**Comment by offerijns** [comment]
> When we create a Pool, we send metadata. If we want to move all metadata related functionality into pools-registry, we have to always have two calls from now on and adjust the create paramaters.

For now, I think the metadata should still be passed to `pools.create`, but `pools-registry` should expose a trait method to update the method and this can then be called by `pools.create`. I think at some point, we can potentially consider entirely moving `create`/`update` to the registry, but this is definitely a much bigger change we should not start on now.

**Comment by gruberb** [comment]
> but pools-registry should expose a trait method to update the method and this can then be called by pools.create

Hm, what would be the advantage? If I introduce a `trait`, which is just used for one other pallet, than we can implement it in the pallet right away! 

We currently use the `pools` storage for the metadata, so how I read this is:

Use the `pools-registry` storage for metadata, but still call the functionality to update this metadata inside the `create` and `update` extrinsic.

**Comment by mustermeiszer** [comment]
> Hm, what would be the advantage? If I introduce a trait, which is just used for one other pallet, than we can implement it in the pallet right away!

what do you mean here? 

@offerijns I think it makes sense to already cur the functionality out. Assuming the logic is as follows: 

* create a pool, without metadata
* pool-registry will expose a Call `add_metadata` and check if the pool exists and if the user has the rights to add metadata (i.e. if he is a pool-admin). 

Not sure what @gruberb thinks about this idea?

**Comment by mustermeiszer** [comment]
My reasoning is: 

* pallet-pools -> system like pallet that is not concerned with additional logic around pools. It stores the core logic and is able to `release` updates via the future `UpdateGuard`. 
* pallets adding additional information to a pool can always use `PoolInspect` and `Permissions` to check whether a change is possible.
